### ISSUE TITLE
Allow user to filter Verified and GIVBack eligible projects

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-next#100]
## 📋 Anything to add?

When the project get verified and become eligible for GIVBacks we want to allow users to filter such projects on the homepage and / or elsewhere

**Comment by divine-comedian** [comment]
testing on `next.giveth.io`
looks like projects can be filtered by Verified on the projects page.. 
there is the `trace` tag which helps identify the projects as verified

![image](https://user-images.githubusercontent.com/67759413/125626033-bbbd16cb-fcec-42b7-8ffc-884224112698.png)

**Comment by laurenluz** [comment]
verified projects are the same as GIVback eligible and the filtering works fine... so closing this
