### ISSUE TITLE
As a project owner I want to preview my project

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-next#102]
[Comes from this user feedback](https://app.zenhub.com/workspaces/giveth-2-5ecaa273967d386713036ca4/issues/giveth/giveth-2/592)

> Maybe add donate link to the dashboard of the project, I wanted to see how it worked and had to go to the home page, then projects then click donate they're instead of open, since it's my project it took me to the back end, which is great, it's just my donate link should be there easy to find and open in a new window.

I believe we need a preview link of the project owner page

**Comment by MoeNick** [comment]
@markoprljic do u have an updates on this issue?

**Comment by markoprljic** [comment]
I don't.
