### ISSUE TITLE
Set maximum of 5 on the number of categories a project is able to select

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-next#103]
Allow user to Select or Deselect all categories for Projects. I believe two places, Create a Project and Edit Project. 
![Image 2020-12-09 at 4.29.22 pm.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/c0d1bdf5-4df6-4d37-9a8f-5b76dc3c6c5b)

**Comment by laurenluz** [comment]
niiice, working on live

![image](https://user-images.githubusercontent.com/75490971/131899239-ae9bfe5d-5325-462e-9502-38b32d529f00.png)
