### ISSUE TITLE
Optimize for mobile

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#115]
One of the things that really came under the wheel is display on mobile. Because we use tor.us - mobile client use is totally possible and we should optimze for that.

@RamRamez - This is a great first issue and should help you get a good overview on the application. Please note that you can use the hooks from react-responsive to make this easier - especially if you want to show a whole element or component only on desktop or mobile

**Comment by divine-comedian** [comment]
how can we test this issue @RamRamez  @MoeNick ?
