### ISSUE TITLE
Integrate with Giving Block to score their Verified Projects

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-next#117]
Griff, Dani, Ashley, Lauren and Forest had a call with Alex, one of The Giving Block Founders and got his blessing to take their 400+ projects and add them to Giveth.

These would be verified projects by default.

Here is the API: https://app.gitbook.com/@the-giving-block/s/public-api-documentation/

The MVP Scope would be to just to add all the projects that are there nowTo Giveth as Verified Projects, the Requirements are that they can only accept the Tokens that Gemini accepts on Ethereum https://www.gemini.com/exchange

And the API only gives an ETH address so we will have to scrape their picture and description off the website https://www.thegivingblock.com/donate/Save-The-Children but this may need to be done in a slightly manual way... since the context is different (there is no tax receipt)

We don't need to offer the Tax Receipt stuff to start... but in the future that might be interesting

**Comment by jamespfarrell** [comment]
Wow, that's amazing :)
I can advise on the best way to do this.

**Comment by mateodaza** [comment]
> Wow, that's amazing :)
> I can advise on the best way to do this.

oh oh! wanna discuss it over here or should we meet soon?

**Comment by WhyldWanderer** [comment]
@cquinterom096 to set up a meeting with mateo and james to discuss the best way to integrate.

**Comment by WhyldWanderer** [comment]
@mateodaza @cquinterom096...
I received a response from Alex:
"We generate a new wallet each time for the sake of donor and nonprofit privacy; however, all the wallets generated in the widget can be re-used as often as you'd like. They never expire; however, it will make it harder to track donor info or issue tax receipts because they would all be tied to the same wallet. "

**Comment by laurenluz** [comment]
Hey @CarlosQ96 @MoeNick we discussed this in the GIVeconomy call today, and it would be awesome to get those projects on Giveth whenever we can. Is this all ready to go?

We should indicate somewhere on the project that these came from the Giving Block. @markoprljic can you suggest the best way to to this?

And we need to add a prompt to Tweet and tag Gemini if the user tried to donate GIV to these projects after launch, as per #416

**Comment by CarlosQ96** [comment]
Hello @laurenluz I have worked on this task for a while, but stopped because of other priorities and bug fixing. I only have one issue left and I can take this on again. Probably have it ready over the weekend for testing.

**Comment by laurenluz** [comment]
Sounds great!! I wouldn't say this is high pri, but it's definitely good to get back on our radar since it's no longer blocked.

This weekend would be awesome, but I'll leave it to @MoeNick for the final say on priorities and planning

**Comment by MoeNick** [comment]
@CarlosQ96 I think we can start   Right after the things in staging confirmed as done, like adminbro for production, finalize transak testing and backend support for front new design. 
We also have Mohammad back to io and I think you can start whenever you think you have bandwidth.

**Comment by markoprljic** [comment]
@laurenluz I'm not sure I understand this issue and request. Is there somewhere I can read about how we got to it to get more context about the requirement?

**Comment by laurenluz** [comment]
I don't think it's written clearly anywhere @markoprljic ... a summary:

- We are partnering w Giving Block and going to have all their (awesome & background checked) projects listed on Giveth... and people will be able to donate to through project through our platform
- They will all be considered "verified" on our platform (and donors can get GIVbacks)
- They will only be able accept tokens listed on Gemini (b/c giving block restrictions)
- GIV won't be on Gemini as launch, but we're trying to get it listed

SO, the flow, from #416 

> Giving Block projects to be on Giveth at launch
Well have GIV token as an option for tokens to donate from
When the user selects GIV, something says "this is a Giving Block Project and Gemini doesnt accept GIV tokens"
Implement a popup w a tweet saying something like "I want to donate GIV to this project, but we need gemini to list it!" (tag gemini and maybe cameron & tyler for laughs :) )

We also want to make sure we give nice shout-outs to the Giving Block so I was suggesting that perhaps we have some kind of marker on the Giving Block projects that says they are both:
1. Verified, and
2. From Giving Block

Maybe something like this:
![image](https://user-images.githubusercontent.com/75490971/142500513-dd0bb08e-1c8e-4c66-ab0f-e3ca69ab5ec1.png)

So I would love your help with designing that marker and also perhaps the UI for these notifications and the prompt to tweet

**Comment by MoeNick** [comment]
@laurenluz is it necessary  to add a badge? We may have other integrations on future, I myself  don't suggest we add a badge for each integration with thirdparties. 

And another question: Do we need to do it just once? or do we need to subscribe to updates and edits if their projects too?

**Comment by markoprljic** [comment]
I also don't think we should include the badge.  We can state it somewhere maybe in the project description (within the text of Description at the top hardcoded) but not having a badge on the project card.

**Comment by laurenluz** [comment]
Whether it is a badge or hardcorded at the top of the project description, we should definitely mention it. The Giving Block is doing us a huge favour by providing us with these great projects to put on Giveth, we should give them shout-outs/cred wherever possible as thanks.

I think the badge is much cleaner for three reasons: it doesn't disrupt the flow of what could otherwise be written in their project description, it makes it clear to the donor why there is limitation on the tokens they can donate, and it's a nice homage to the Giving block.

**Comment by CarlosQ96** [comment]
Who should I set up as the admin of these projects? @laurenluz Since I am just exporting basic information I don't have a admin to setup.

**Comment by GriffGreen** [comment]
@CarlosQ96 I think we should have a Key that is the admin to all The Giving Block so that we can better support that set of users.

How do we manage auto updating their projects? Does the Admin key need to do that? 

The Admin key can pass its ownership over the project to someone else right?

**Comment by GriffGreen** [comment]
RE: Giving Block Tag. @laurenluz @markoprljic @MoeNick  

Hell yes let's get the words "The Giving Block" in the eyes of our users right away, on our front page.

I can't say enough how important it is for the network effect and our general reputation and high gratitude vibes that we go over and above to give credit to groups like The Giving Block.

The Giving Block has their whole team dedicated to on boarding charities to web3, they are HEROS! I hope they will apply for funding from the GIVgarden to do what they are already doing and we can support them. 

We are setting our selves up to be THE Giving Economy and we have to be extra careful not to feel like we are competing with anyone. We should be our "Competitors" #1 cheerleaders in every way to avoid that very easy trap.

We can't for a second let the Giving Block think we are taking advantage of their service and not giving them the props they deserve.

**Comment by markoprljic** [comment]
@MoeNick Please let's not make rushed design decisions. I'll prepare a design solution for this soonest.

**Comment by CarlosQ96** [comment]
> @CarlosQ96 I think we should have a Key that is the admin to all The Giving Block so that we can better support that set of users.... Maybe Ashley and I can share holding the key?
> 
> How do we manage auto updating their projects? Does the Admin key need to do that?
> 
> The Admin key can pass its ownership over the project to someone else right?

The project admin is configurable from the adminbro, I'll double check if that works fine, if not I'll add that functionality. But yeah we can create a specific admin for this and have the credentials shared between Ashley and Griff.

On the auto updating,  we have to decide if we periodically re-sync them from their API.
Or only allow the admin to update their description/basic-info. 

We should go with one, I want to avoid overwriting updates. (example: admin changes the description and then I re-fetch it from the api, overwriting the description).

**Comment by MoeNick** [comment]
@markoprljic So if its not rushed, please make it standard design for further integrations might we have in future and also have the same flow for new UI design.

**Comment by markoprljic** [comment]
Project Card in the list
![Image 2021-11-30 at 3 30 39 pm](https://user-images.githubusercontent.com/5704285/144066159-65d41577-eefe-4b84-afa1-3f848312db35.jpg)


Project Details page
![Image 2021-11-30 at 3 27 20 pm](https://user-images.githubusercontent.com/5704285/144065582-4a760911-33a9-45ad-a9b2-17538e2ea76a.jpg)

**Comment by laurenluz** [comment]
@markoprljic can you also create the UI for the prompt to tweet?

- Giving Block projects will be on Giveth when we launch the GIVeconomy, but can't accept GIV tokens until Gemini lists it
- We will have GIV as an option in the token drop down
- If the user selects GIV, they get an alert, tooltip or popup giving them the option to tweet.
- Text for alert: "Giving Block projects only accept donations listed on Gemini - Help us get GIV on Gemini!" And it can have a little twitter symbol.

Tweet says

> Hey @ gemini - I want to donate $GIV to this @ thegivingblock project on @ givethio! Help me support them by listing $GIV on gemini.com
> 
> @ tyler @ cameron 
>
> [link to project page]

**Comment by markoprljic** [comment]
![Image 2021-12-01 at 2 30 33 pm](https://user-images.githubusercontent.com/5704285/144243094-2c839a8f-13d6-4289-8d24-ec2d7855db1f.jpg)

**Comment by laurenluz** [comment]
Niiiiiiiiiiice 🚀

**Comment by WhyldWanderer** [comment]
Here is the profile for the project owner of the Giving Block projects @MoeNick @CarlosQ96 

0x07e995f06149352015BDe16530169cab76EF58FE - The Giving Block + Giveth = <3

Currently the email is set to info@giveth.io and I have asked Kay to create one just for this - givingblockprojects@giveth.io

**Comment by CarlosQ96** [comment]
@MoeNick @GriffGreen @WhyldWanderer  Leaving a status report Here:
Total GivingBlocks Projects: 762
Projects that accept anonymous Donations: 719
Projects Exported: 713
Projects that do not accept anonymous donations: 43
Projects that do not work in the API or Website: 6 

We have to decide what to do with the 43 projects that do not accept anonymous wallet addresses donations, which is the type of address I am setting for the projects on Giveth.

Regarding the 6 projects that don't work, as they don't allow creating Wallet addresses on the website, I'd say skip them for now or ask GivingBlocks Support to check on them.

**Comment by divine-comedian** [comment]
is this issue ready to be tested? are the comments above resolved? what does success look like?

**Comment by CarlosQ96** [comment]
Yes this was tested in production by Ashley and Griff, they added donations to the projects.
And the GivingBlocks team confirmed the donations in their backend.
We modify some projects in the adminbro for a certain organization and everything was fine.

**Comment by divine-comedian** [comment]
@CarlosQ96  is this issue done then?

**Comment by CarlosQ96** [comment]
yes :D
