### ISSUE TITLE
White space under main post

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#120]
**Please describe the issue or bug you are experiencing:**
White space under main post
![image]()

**Comment by mateodaza** [comment]
I can't see the image man :( what was it?

**Comment by WhyldWanderer** [comment]
The user must not have uploaded a screenshot or it would show up automatically within the issue.

**Comment by MoeNick** [comment]
is it possible to see the screenshot or we cant right know?

**Comment by WhyldWanderer** [comment]
Unfortunately, there is no way to get more information from the user because they didnt provide a screenshot or an email address to contact them at.
