### ISSUE TITLE
Error on project listing

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#122]
**Please describe the issue or bug you are experiencing:**
error on project listing. link broken. I have screenshot
![image](https://api.typeform.com/responses/files/0d548890c0f098c73d364e788a52f2cdc4f2abeb3b3a917beab3032cc335939b/giveth_error.png)

**Comment by mateodaza** [comment]
For some reason this project was saved with this slug 'ETHOS-Emergency-Transitional-Housing-Offering-Services-1'

Yours doesn't have the -1

weird
