### ISSUE TITLE
Remove "New" marker on projects that are not new, and add verified marker

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#130]
I remember talking about this with @markoprljic at some point, but can find the issue for it.

Currently, all projects say they are "New"
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d7baf4b5-a56e-48d3-9e6a-03714ed543b5)

Let's have the "New" label disappear after a period of time (say... 2 weeks? 3 weeks?). If the project is verified it can have a "Verified" label in its place. If not, then nothing.

@markoprljic what do you think?

@mateodaza tagging you so you got :eyes: on it

**Comment by mateodaza** [comment]
yesss good one! I'll start by doing the filter by 2 weeks, and also put the verified icon besides the title or somewhere there

**Comment by laurenluz** [comment]
you are a magic man 🌟

**Comment by divine-comedian** [comment]
testing on `next.giveth.io`

looks like new projects have a `new` tag on them and older projects no longer all have this tag. 

I couldn't find any tags for verified projects except the `TRACE` tag which links to a giveth TRACE project
![image](https://user-images.githubusercontent.com/67759413/125631489-7e11e989-2773-46b9-a735-c73a7f219448.png)

**Comment by mateodaza** [comment]
there are no verified projects on staging, check it out on live ;)
