### ISSUE TITLE
TOKEN DECIMALS ARE WRONG!! UH OH! 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-next#142]
## 📋 Anything to add?

Token Decimals should not be assumed... TheDAO tokens had 16, USDC has 6, lots of tokens have 8.... most have 18 but it's a very very dangerous assumption.

![Screen Shot 2021-07-12 at 10.56.35 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/17b16722-93f0-4bc0-b19f-c8fdc685a31a)

Pull the decimals out of the token contract please

## ⏰ Urgency/Deadline/Blockers?

Urgent

## ❓ Why is it important?

This could lead to loss of funds... critical bug

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by GriffGreen** [comment]
I think we should hot fix USDC... but should then make sure the decimals are pulled from the contract and we don't guess

**Comment by mateodaza** [comment]
I'm working on this, we are pulling the decimals from coingecko but I think the metamask interaction doesn't take it into account. I'll get it up ASAP

**Comment by divine-comedian** [comment]
I'm unable to test this issue because giveth.io doesn't allow me to use USDC on ropsten

**Comment by divine-comedian** [comment]
testing on `next.giveth.io` on xDai Network 
got USDC and donating to a project the MM screen shows up and correctly confirms the 1 USDC that i specified to donate. No surprises. Also tested with 1 USDT

![image](https://user-images.githubusercontent.com/67759413/125654578-8748af29-c00b-4853-b3af-a947b427862f.png)

![image](https://user-images.githubusercontent.com/67759413/125658330-56da1b5d-67f9-4347-a044-de61938c2c82.png)

also also who ever owns this campaign has 1 USDC in their wallet ..... oops
