### ISSUE TITLE
My projects don't show up on the projects page! 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-next#145]
## 📋 Anything to add?
I made a couple of projects in the last couple of days on `next.giveth.io` and I tried to find them on the projects page and they are nowhere to be found! 
After further investigation I found out there was a bunch of my projects missing from the project page, I couldn't find them in the unfiltered list or using the search function. They do show up in `My Projects` and are active projects (not deactivated)

At least these projects that I know of are affected: 
https://next.giveth.io/project/does-my-project-show-up
https://next.giveth.io/project/my-new-project
https://next.giveth.io/project/surely-i-am-not-a-contract

EDIT: 
After further testing I found that I had to clear cache and cookies in order to get one of my projects to show up after I created it - https://next.giveth.io/project/does-my-project-show-up

**Comment by MoeNick** [comment]
@divine-comedian shall we close it?

**Comment by divine-comedian** [comment]
very old issue - looks to be resolved
