### ISSUE TITLE
Project doesn't update after editing

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-next#146]
## 📋 Anything to add?
Testing out editing projects on `next.givethi.io` 

I tried re-activating  and editing the titles of a few of my projects and made some new projects on giveth.io 

the changes were not reflected immediately on the projects page, some cases it was impossible to find my project or it was showing up with the old title and leading me to a broken page (because the project slug and title has changed, causing a broken query)

I had to clear cache and cookies in order to get my projects to show up correctly, this may be confusing for users however. 

projects I tested with- 
https://next.giveth.io/project/testing-another-project
https://next.giveth.io/project/trying-to-change-the-title
https://next.giveth.io/project/does-my-project-show-up

is this normal behaviour?

**Comment by mateodaza** [comment]
Nice find! @cquinterom096 can you help me check the mutation on the graph?

**Comment by mateodaza** [comment]
The slug change is already fixed. The *not instant* change is because of cache, it shouldn't take more than a couple of minutes. Should we allow the user to know this with a message or something?

**Comment by divine-comedian** [comment]
from this screen here that already pops up - 
![image](https://user-images.githubusercontent.com/67759413/129223607-a8d7dd78-991b-4544-8d35-8e651e390f18.png)

suggesting to modify text to : 
`Success! Please allow a few minutes for your changes to be displayed.`

**Comment by laurenluz** [comment]
New text was added, nice touch, guys:

![image](https://user-images.githubusercontent.com/75490971/130523905-b45a3b40-fa41-49f0-9107-076317a5c554.png)

and updates work fine
![image](https://user-images.githubusercontent.com/75490971/130524011-120bcbc4-19f9-4144-a5ec-83893af94480.png)
