### ISSUE TITLE
Add Forum to Join Page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#147]
## 📋 Anything to add?
Now that we have the Forum active it would be cool to link it to our Join page.

I created a little mockup in paint of what it could look like. The formatting isnt perfect and the text might need a review but it will help to have a visual.
![image](https://user-images.githubusercontent.com/74267818/126082199-f3ca5660-cadd-4c92-8438-ef230d19efd3.png)

## ❓ Why is it important?
To solicit engagement from community members in the Governance process as well as allow people to provide ideas, proposals, and new user perspective.

**Comment by MoeNick** [comment]
@divine-comedian 
Shall I move it back to backlog? any progress?

**Comment by divine-comedian** [comment]
I have opened and began investigating this issue but haven't had time to implement a solution, likely I won't get to this until next week.

**Comment by divine-comedian** [comment]
LIVE

![image](https://user-images.githubusercontent.com/67759413/132525129-1107fdaa-c95c-4a08-93e0-4a20dc32bb8b.png)
