### ISSUE TITLE
Projects are not showing up on the my projects page in my account

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#149]
When I navigate to 'my projects', my project does not show up.
![image](https://user-images.githubusercontent.com/74267818/126803474-cc3fbaf6-e87c-4d59-baed-383d6a6cbf39.png)

![image](https://user-images.githubusercontent.com/74267818/126803403-ec0b1443-d051-4041-90c1-3d7bab19f817.png)

But when I go directly to the project page, I can see the edit button and add updates etc.
![image](https://user-images.githubusercontent.com/74267818/126803497-53462df0-1f84-4bb9-8570-c9aa4baf20cc.png)

This is happening with 2 accounts/projects that I own.

**Comment by laurenluz** [comment]
@RamRamez @mateodaza This is similar to the issue that another project was having on live today that I mentioed to you about

This is the project:
https://giveth.io/project/Oika-in-the-Blockchain-1

Can we try to get this fixed up soon?

**Comment by RamRamez** [comment]
Issue [#902](https://github.com/Giveth/giveth-2/issues/902) is related to a bug with Quill component initialization that I resolved in PR #244. @laurenluz I don't think they are related.

I checked my accounts and my projects is listed correctly. @WhyldWanderer Please check again if you still can't see your projects in my projects page.

**Comment by WhyldWanderer** [comment]
I just checked... and this is working for new :)
