### ISSUE TITLE
Traceable projects on Giveth.io - can't "like" or view # of donations

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#157]
There's no option to "like" the project... I think we should add that in

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/49f8fcc2-ca0d-4424-8d46-7ba7624d9edf)

Also... is it possible to list the number of donations? can we get that data from giveth TRACE and show it on giveth.io? @aminlatifi

**Comment by MoeNick** [comment]
We have subscribe, but not  have like concept on trace.
Yes all the data fir campaign can be showed here, we plan for it but I think Mateo needs design. I suggest adding trace tab beside donations to show traces, and we also list donations below donation tab.

**Comment by MoeNick** [comment]
@laurenluz lets more discussions to #137

**Comment by aminlatifi** [comment]
> There's no option to "like" the project... I think we should add that in
> 
> ![image.png](https://camo.githubusercontent.com/609289109598a70303570a5980e5f4bd58e62a747e5649f47cdb110986f83891/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566646661633136613538353233613836366464623638642f34396638666363322d636130642d343432342d386434362d376261373632346439656466)
> 
> Also... is it possible to list the number of donations? can we get that data from giveth TRACE and show it on giveth.io? @aminlatifi

The `like` feature is not available in Giveth Trace, to have it we may implement something in impact-graph (giveth.io backend)

**Comment by MoeNick** [comment]
Currently, I assume we support traceable projects in io backend, so we can add liking to them. Am I right? @mateodaza

**Comment by laurenluz** [comment]
closing as per discussion in forum: https://forum.giveth.io/t/no-action-change-campaign-to-project-on-giveth-trace/114
