### ISSUE TITLE
Quality score parameter research

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-next#161]
## 📋 Anything to add?
what's the best way to calculate the quality of submitted projects on IO

## ⏰ Urgency/Deadline/Blockers?
Very important but not urgent

## 🔗 Work doc - inspirational links
https://forum.giveth.io/t/make-our-giveth-io-dapp-more-resilient-before-giveconomy-deploy/73

**Comment by MoeNick** [comment]
Test Scenario:
User can only see quality projects on the list.

**Comment by MoeNick** [comment]
@laurenluz  @mateodaza can we make sure we pass scoring doc at the end of this sprint of forum?

**Comment by laurenluz** [comment]
we've got a proposal up on the forum with our suggestions...
https://forum.giveth.io/t/revise-quality-score-for-projects-on-giveth-io/104

will close this issue as the "research" is perhaps done... just need to come to agreement and then put it in practice.
