### ISSUE TITLE
Social Media link buttons not working on Donation Success page

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-next#163]
Twitter, LinkedIn and FB buttons do nothing:
![image](https://user-images.githubusercontent.com/39466970/129068527-eb99b590-1d9c-480b-b05c-43c8a331c245.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by divine-comedian** [comment]
I'd like to take a stab at this one
