### ISSUE TITLE
Top Donation project not showing in filtered list

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-next#164]
When I sort by 'ALL' then "Amount Raised" .. this new BlockFish project is first, then Giveth then Bridges:
![image](https://user-images.githubusercontent.com/39466970/129071919-9369672f-3bf8-4140-8c8f-e9a846ab8da4.png)

But this verified project used to be at the top, has raised the most, and isn't even in the list anymore:
![image](https://user-images.githubusercontent.com/39466970/129071265-3cda7f97-355d-4439-a8ee-ce86d9af25d4.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
Good catch, I believe it's sorting by amount of donations and not amount donated. 
Will fix, thanks for noticing Dani!

**Comment by Danibelle** [comment]
Pleease..  I have a presentation tomorrow and am telling the story of this project to raise funds 😅

**Comment by Danibelle** [comment]
fixeded closing thank you!
