### ISSUE TITLE
Change Text on "Ask a Question" in support page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#178]
Should say "Do you have a specific question or a general inquiry that requires a response?"

Reference #49

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/f1b6f13b-bf49-424a-8cc7-75b23c758063)

**Comment by mateodaza** [comment]
I believe this is coming from contentful, not sure who has access to that besides @geleeroyale

**Comment by geleeroyale** [comment]
I believe so as well - will have a look.

**Comment by divine-comedian** [comment]
looks to be fixed! 

![image](https://user-images.githubusercontent.com/67759413/132519892-b27e112b-0feb-4c61-9bc8-64543565290d.png)
