### ISSUE TITLE
FORM: I created a project with quotes in the title and it screwed up the link

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#179]
**Please describe the issue or bug you are experiencing:**
I created a project with quotes in the title and it screwed up the link
![image](https://api.typeform.com/responses/files/73b510847b208ec5a859184fc66681ce44f2dd2189bc5fc7010aede2a7f35370/Screen_Shot_2021_08_24_at_6.20.33_PM.png)

**Comment by mateodaza** [comment]
this is fixed, we are only accepting letters and numbers for project titles
