### ISSUE TITLE
FORM: Bug/Issue - I was "signed in" to giveth.io as in but it wouldn't authenticate me

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#180]
**Please describe the issue or bug you are experiencing:**
I was "signed in" to giveth.io as in  but it wouldn't authenticate me... I had to sign out and then sign back in to get the signature window to pop up... It would be great to have a Confirm Signature button somewhere to avoid this issue... or when authentication fails, automatically pop up the signature window
![image]()

**Comment by MoeNick** [comment]
I had the same issue, specially after I change my address or lock my wallet.
