### ISSUE TITLE
Gitcoin round 11 banner to encourage donations

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-next#183]
Following this issue on our planning https://github.com/Giveth/giveth-planning/issues/321

Design: https://www.figma.com/file/FBqHg0UfeuaIueDEZG0tBS/Giveth.io?node-id=970%3A1

**Comment by laurenluz** [comment]
SO DREAMY - love the animation

![image](https://user-images.githubusercontent.com/75490971/131900159-5ff65484-129a-4001-80f5-16ef3180d9dd.png)
