### ISSUE TITLE
Error when click on "How To Write A Great Project Description"

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#198]
In creating a new project, in description tab, when click on "How To Write A Great Project Description"
I got this: 

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/5013f434-5052-4b9c-b096-29f3bcba0d26)

**Comment by RamRamez** [comment]
Done in PR #223 

For UAT testing:

1. Fix error when clicking how to write a great project description
2. Improve "Create Project" responsiveness

**Comment by laurenluz** [comment]
confirmed - works great on next
