### ISSUE TITLE
shoud pass all steps again if I want to edit just an step. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#204]
When I want to confirm my provided data, when I click on edit I went to specific step, back after clicking next, I go to next step instead of getting back to confirmation page. 
It's a ux not a bug.  

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/da44b3cc-efda-4955-8e72-bd245b49294e)

**Comment by markoprljic** [comment]
Addressing this in the redesign.

**Comment by aminlatifi** [comment]
It's addressed in design
