### ISSUE TITLE
Setting listed / unlisted in Backoffice for every projects.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#207]
As a Givether (or giveth admin) I want to change the option of being listed / unlisted for every project so I make sure my project list is resilient of preanal spams. 

Acceptance Test Scenario:
1- I see login page 
2- By connecting my wallet, I can login as system administrator. 
3- I should see a suitable error msg when my wallet is not whitelisted as an admin.
4- I may see a list of projects in a list, default sorted by date, newest on top. 
5- In the table I see their slug, create date, creator, status and listed / unlisted. 
6- I may search the result by slug and filter project by date (from - to) , listed/unlisted - creator - status
8- I may be able to sort the table by date, slug (alphabetic), status
9- There will be operator at the end of each row (project) letting me change the listing option.
10- I can select multiple rows by checking a checkbox and change their listed / unlisted status in group.  
11- I see a notification and confirmation pop-op for changing listing / un-listing status, both group changing and per project changing.
12- I can log out

**Comment by MoeNick** [comment]
@laurenluz @mateodaza 
Love your comments here.

**Comment by mateodaza** [comment]
Rather login with a wallet instead of user/pwd. We'd have a whitelist of admins that can sign it and that's it.

Everything else seems fine

**Comment by MoeNick** [comment]
@mateodaza done.

**Comment by MoeNick** [comment]
@mateodaza would u pls comment what you choosed, , related PRs etc. 
Cause it may have side effect of Trace entities, @mohammadranjbarz gonna work on related services.

**Comment by mateodaza** [comment]
Can I move this? If we wanna add this to trace that should be another issue

**Comment by MoeNick** [comment]
I just want to make sure Admin Bro is tested on Staging. 
@mateodaza would u pls give access to someone truct to have a strict testing on it?

**Comment by divine-comedian** [comment]
@CarlosQ96

**Comment by mateodaza** [comment]
I believe this is done @MoeNick @CarlosQ96 please confirm

**Comment by CarlosQ96** [comment]
This is done correct. There is no filter by slug but there is by title I think that should be ok for now.
