### ISSUE TITLE
Updates don't show date of posting

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#22]
Instead all updates (except Project creation) show the current date.

![image](https://user-images.githubusercontent.com/317685/120214969-795b1680-c235-11eb-8cb7-8ec190c4fe48.png)

**Comment by laurenluz** [comment]
excellent
![image](https://user-images.githubusercontent.com/75490971/122269477-7d746e80-ce9a-11eb-837a-c723132613d3.png)
