### ISSUE TITLE
Make "no image" projects have "no image" (not the Giveth logo)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#231]
Right now the default image when a project creator puts NO image is "Giveth"... I really think we should change that... we shouldn't put our brand up with no-image projects.

Can we add a grey screen with "no image available" or something like that? Something like this on the project card:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/10034a25-0168-432d-977f-9e70a18dc759)

It looks like this right now on the project's page:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/9a8daca0-41a4-4147-ac01-ab5bd8e43d41)

**Comment by RamRamez** [comment]
Done in PR #240

**Comment by laurenluz** [comment]
it's fixed, but a little strange!! can we have it just have "no image available" appear once in the center? rather that it repeating with different formatting?

![image](https://user-images.githubusercontent.com/75490971/135932096-f7b3bf35-4549-4065-bba8-8a32a00257ee.png)

**Comment by RamRamez** [comment]
@laurenluz You mentioned a good point. I fixed it in PR #287 

![image](https://user-images.githubusercontent.com/73441857/136002471-c7e28d46-5585-4bf8-becb-86d693042f19.png)
