### ISSUE TITLE
Add link to switch to xDAI network

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#24]
As a user I want to click how to donate using xDAI, but I just get the information that I can do it without telling me how to go about doing it:

![image](https://user-images.githubusercontent.com/317685/120234646-b71d6680-c258-11eb-80b2-7cd8bc68be09.png)

We do have a hint buried in the [user-guide section of the docs](https://docs.giveth.io/guides/donatingmetamask) (thanks @divine-comedian), but it should be its own article going more into depth.

![image](https://user-images.githubusercontent.com/317685/120234998-68bc9780-c259-11eb-9c8c-0bf06f9f2912.png)

**What I really want** is to **click the thing** and then be able to **switch the network**, if that is not possible a little video clip of changing the network and signing in with metamask would go a long way.

**Comment by divine-comedian** [comment]
@geleeroyale are you suggesting a guide for getting xdai? and I suppose you mean a little gif or something similar as in TRACE for switching to ropsten/rinkeby?

**Comment by geleeroyale** [comment]
The latter. I think we can leave out how to actually get xdai - but we should tell people that they need to be signed in on the xdai network if the want to donate a token from there.

**Comment by markoprljic** [comment]
Add "Switch Network" link after the sentence, when clicked popup MM that asks to switch to xDAI.

**Comment by divine-comedian** [comment]
testing on `next.giveth.io`
brave browser clean cache and cookies

switch network button shows up on UI, I click the button and it successfully changes my network from ropsten to xDAI. 

![image](https://user-images.githubusercontent.com/67759413/125627127-ecb5b179-00ca-4719-bb22-b7dc0ef05abd.png)

nice work!
