### ISSUE TITLE
raw URL in tab header/metadata for project donate pages

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-next#252]
## 📋 Anything to add?
currently on production and next.giveth.io 

the title in the tabs when on the donate page for a project is showing the raw URL, while when simply viewing the project page there is a custom title with the project name in the metadata 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/f8f117d3-b4d4-4df7-9875-fd15a32c982b)

We should implement something similar to the project page where the metadata for the title is 

"Donate to {projectTitle)"

**Comment by divine-comedian** [comment]
I'd like to try fixing this one

**Comment by MoeNick** [comment]
Good catch. 🥇
