### ISSUE TITLE
Blockchain provider: Web3 – ether.js

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#269]

**Comment by mateodaza** [comment]
@RamRamez this is done, right?

**Comment by RamRamez** [comment]
> @RamRamez this is done, right?

No this is not. Now we are using both web.js and ethers.js and those are doing the same thing. Those packages are about 5.7MB and 10MB so it would be better to unify the code and use one of them.

**Comment by mateodaza** [comment]
how do we make the decision? you have any opinion?
Found this interesting [blog](https://blog.infura.io/ethereum-javascript-libraries-web3-js-vs-ethers-js-part-i/)

**Comment by RamRamez** [comment]
> how do we make the decision? you have any opinion? Found this interesting [blog](https://blog.infura.io/ethereum-javascript-libraries-web3-js-vs-ethers-js-part-i/)

Yes, and the number of downloads in NPM are very close, both 400,000 per week.

I think you can also check the the code and see which one is less used. The one that is less used in our code would be easier to change.
