### ISSUE TITLE
Add popup prompting donors (w incomplete profile) to complete their profile after donating

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#272]
On this page:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d4ed5316-81f2-4aee-b8fa-784c2c17a923)

When an anonymous donor donates, or when a donor who didn't fill out their profile donates... add a popup that asks them for their email. It should say:

**Complete Your Profile**
Add your email to keep track of your donations on Giveth as well as stay informed about donor opportunities, new features, and the upcoming GIVeconomy!"

Then a field for them to input their Email, a button that says "SUBMIT" and a small text underneath that says "No thanks"

Like this:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/011e3944-464d-4af2-8f13-71c42286f5fa)

**Comment by laurenluz** [comment]
@RamRamez @mateodaza 

whoever picks this up, let me know if you have questions! This is coming from the comms team as a desire to create a "donors" email list. right now most donors aren't really adding their emails, so we want to create the opportunity for it :)

**Comment by RamRamez** [comment]
@laurenluz 

1. What do you wanna tell user in the popup? Is the text for body and buttons ready?
2. Where do we wanna save/send the email address? in IO database?

**Comment by laurenluz** [comment]
@RamRamez 

The text is ready! I wrote it in the issue. here it is again:

**Complete Your Profile**
Add your email to keep track of your donations on Giveth as well as stay informed about donor opportunities, new features, and the upcoming GIVeconomy!"

Then a field for them to input their Email, a button that says "SUBMIT" and a small text underneath that says "No thanks"

**Comment by laurenluz** [comment]
We want to use the emails in autopilot, so I think that they need to be save in the IO database and then autpilot creates a contact for them (or updates and existing contact). That's what Ashley said - she knows better than me,

Maybe @divine-comedian can confirm?

**Comment by RamRamez** [comment]
@mohammadranjbarz 

What do you think? Can we add a new route in the backend to send anonymous users email address? and about DB, any blockers?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz
> 
> What do you think? Can we add a new route in the backend to send anonymous users email address? and about DB, any blockers?

@RamRamez 
I think there is no blocker, I just should look at the tables and mutations  to see what should I do, 
I'll let you know

**Comment by laurenluz** [comment]
Perfect - thanks guys!

**Comment by RamRamez** [comment]
@laurenluz What if we just suggest user to sign up?

The current "Register an account" link on donate page doesn't suggest to complete profile.
We can put a message to suggest user to sign up with a "Sign up" button.
After clicking we show the sign up popup like this:

![image](https://user-images.githubusercontent.com/73441857/135760544-709d17ce-f1f6-430b-af88-c8429cb8864b.png)

**Comment by laurenluz** [comment]
That would be ok... but what we are specifically looking for is to collect emails for donors on Giveth, so we can create and email list for comms.

Maybe we can also add two checkboxes... like "I am a donor" "I am a project maker" and the user has the option of saying what they identify as they sign up and we can use that for the email lists. what do you think?

**Comment by RamRamez** [comment]
@laurenluz We can simplify it for users by just showing the required fields, like:

![image](https://user-images.githubusercontent.com/73441857/135770477-80b41c9b-b7c1-4a03-b32f-d9a854cdd6bd.png)

**Comment by laurenluz** [comment]
Sure, but can you use this text?

> 
> **Complete Your Profile**
> Add your email to keep track of your donations on Giveth as well as stay informed about donor opportunities, new features, and the upcoming GIVeconomy!"

Then a field for them to input their Email, a button that says "SUBMIT" and a small text underneath that says "No thanks"

**Comment by RamRamez** [comment]
@laurenluz Yeah we can use it, maybe like this:

![image](https://user-images.githubusercontent.com/73441857/135770917-c15396e7-d6b8-4593-a72c-b6c5af0ef1bd.png)

**Comment by laurenluz** [comment]
yeah peeerfect!! and this will pop-up after someone without a complete profile donates, right?

**Comment by RamRamez** [comment]
@laurenluz Yeah, good idea.
