### ISSUE TITLE
Check project title validation when editting project (like create project)

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-next#280]
related Giveth/impact-graph#149

https://github.com/Giveth/impact-graph/issues/149#issuecomment-933057897

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
it's ready for test

**Comment by divine-comedian** [comment]
testing on `next.giveth.io`

I try to edit my project title and add in special characters , I get the notification saying I can't use special characters and I'm prevented from updating my project. from what I can see this seems to solve the problem!

![image](https://user-images.githubusercontent.com/67759413/135897902-f236feb3-541d-4071-a44d-83fb48e21f2a.png)
