### ISSUE TITLE
Error when visiting project profile: WebSocket Instance has been destroyed

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-next#307]
Just logging this error. I haven't been able to reproduce it yet, but will report back if I do.

This error occurred when I clicked on the https://giveth.io/project/amw-fund from https://giveth.io/project/

![screencapture-giveth-io-donate-amw-fund-2021-10-13-21_59_01](https://user-images.githubusercontent.com/26232238/137249408-da636368-b86c-4b33-a6ba-237388f6b5ed.png)
<img width="923" alt="Screen Shot 2021-10-13 at 9 59 18 PM" src="https://user-images.githubusercontent.com/26232238/137249447-a830533c-02a2-4824-889d-58879146b8b0.png">

**Comment by MoeNick** [comment]
@MohammadPCh @mateodaza can u pls take a look?
