### ISSUE TITLE
Transak front-end integration 

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-next#308]
Following this docs
https://www.notion.so/Integrate-Transak-f43cbb5dc7fa4d068a044ef9589879bf

It needs this PR to be approved on the backend https://github.com/Giveth/impact-graph/pull/162

**Comment by mohammadranjbarz** [comment]
> @GriffGreen do u have any idea? Can we provide test payment cards or so?

We have 2 test payment cards, I have written them in above comment, it doesn't need any real data in test environments

**Comment by divine-comedian** [comment]
I got as far as putting in the KYC ... I tried to use the test SSN and it threw this error 

![image](https://user-images.githubusercontent.com/67759413/139590715-a352cda2-22f6-431f-866e-a02172195b89.png)

not sure how to proceed @mohammadranjbarz

**Comment by divine-comedian** [comment]
Finally I swapped out the address for one from Florida, I successfully am taken to the payment status modal page, it seems to load indefinitely. I refresh and retry, I'm taken to a modal page to resolve my pending transaction.. and then finally it is successful! 
 
![image](https://user-images.githubusercontent.com/67759413/139592283-f89ab3f3-7fa0-469c-b192-2aa3849b8841.png)

**Comment by divine-comedian** [comment]
I have no way however to see this transaction on the blockchain, since my wallet address isn't provided.  when I click view transaction details I'm taken to an etherscan page that says `No matching entries` and also doesn't show up when I click view your donations.

**Comment by CarlosQ96** [comment]
@divine-comedian since they are test transactions I don't think they should show up in etherscan.

**Comment by divine-comedian** [comment]
> @divine-comedian since they are test transactions I don't think they should show up in etherscan.

okay so the issue is there's no way to test how/if fiat transactions will appear to the user so that donors  can have confirmations via the giveth UI that their donation actually happened.  

Looking up the project I donated to it seems that the donation was made anonymous... but according to the new onboard js flow we should be forced to sign in if we have an affiliated identity.  Also the donations seem to show up twice on the UI. 

![image](https://user-images.githubusercontent.com/67759413/139596217-0da1ef1c-86ad-4a07-8b6e-325168cba835.png)

**Comment by mohammadranjbarz** [comment]
> > @divine-comedian since they are test transactions I don't think they should show up in etherscan.
> 
> okay so the issue is there's no way to test how/if fiat transactions will appear to the user so that donors can have confirmations via the giveth UI that their donation actually happened.
> 
> Looking up the project I donated to it seems that the donation was made anonymous... but according to the new onboard js flow we should be forced to sign in if we have an affiliated identity. Also the donations seem to show up twice on the UI.
> 
> ![image](https://user-images.githubusercontent.com/67759413/139596217-0da1ef1c-86ad-4a07-8b6e-325168cba835.png)

Actually, you have donated twice 

```
{
        "id": "314",
        "amount": 22.45,
        "fromWalletAddress": "0x085ee67132ec4297b85ed5d1b4c65424d36fda7d",
        "toWalletAddress": "0x5d28fe1e9f895464aab52287d85ebff32b351674",
        "currency": "DAI",
        "transactionId": "a7a95813-c893-4a0c-8614-46d633830e23",
        "transactionNetworkId": 1,
        "status": "pending",
        "transakStatus": "COMPLETED"
      }
```
https://kovan.etherscan.io/tx/0x3f3e9b8123347761c32bee9bc3eecd0fc10cce2f86c8426e342e177f529150f4


```
 {
        "id": "316",
        "amount": 22.45,
        "fromWalletAddress": "0x085ee67132ec4297b85ed5d1b4c65424d36fda7d",
        "toWalletAddress": "0x5d28fe1e9f895464aab52287d85ebff32b351674",
        "currency": "DAI",
        "transactionId": "2ea0ccba-93fa-4b7a-ae23-19ceede631e6",
        "transactionNetworkId": 1,
        "status": "pending",
        "transakStatus": "COMPLETED"
      }
```
https://kovan.etherscan.io/tx/0x6c3ff3377e43f1e9d3626a7a952e135ed345c588db1485595d1f6c6f1dc45149

**Comment by mohammadranjbarz** [comment]
> @divine-comedian since they are test transactions I don't think they should show up in etherscan.

I understood when transaction become `COMPLETE` transak give us the transaction link as https://kovan.etherscan.io/tx/0x6c3ff3377e43f1e9d3626a7a952e135ed345c588db1485595d1f6c6f1dc45149
so I would create a PR to persist it in DB

**Comment by CarlosQ96** [comment]
Ok got it. Will be testing this new attribute to see if it's sent in the webhook. It's not documented in Transak docs.

**Comment by CarlosQ96** [comment]
Tested Mohammad's Branch, indeed transak only sends the transaction link when it's completed. We will be merging the changes.

**Comment by mohammadranjbarz** [comment]
@MoeNick 
 The transak stage environment is not stable enough
 I could donate till few days ago but now I get error when donating
 
 
![Screen Shot 1400-08-10 at 17 55 17](https://user-images.githubusercontent.com/9850545/139687527-7ee39ada-e545-479a-ab20-07857ced5fe2.png)

**Comment by MoeNick** [comment]
![image](https://user-images.githubusercontent.com/80677512/139688305-e521decc-6812-4388-9fb5-25e9ce301d7b.png)
I just send them a msg on Telegram. waiting for their response. 
You can do so on @Amandoshi

**Comment by CarlosQ96** [comment]
I remember a week and a half ago I had the same issue, remember we spoke in the meetings that Transak was down. Seems related to this, they just told me its up again, but not really any indication of stability whatsoever.

**Comment by divine-comedian** [comment]
@CarlosQ96 @MoeNick  is there any update to test this issue?

**Comment by MoeNick** [comment]
@mateodaza supposed to talk with them. I couldnt, they didn't answer me.
@DonnaOftadeh appreciate if you can test and update us here

**Comment by mateodaza** [comment]
This is ready for testing on staging using this info

![image](https://user-images.githubusercontent.com/18689480/143043565-37f1231b-ffed-459f-a792-77eb09445d94.png)

**Comment by DonnaOftadeh** [comment]
I am testing it,
0. The loading is really slow, it seems nothing is happening while loading, we need a loading icon:
![image.png](https://images.zenhubusercontent.com/60f71f99b9da54ac7e274e9d/f0b1b7fc-2417-4bfe-8f06-b0701afa04f7)

1. it set a default amount (300 euro in my case) which as a donor I don't like :
![image.png](https://images.zenhubusercontent.com/60f71f99b9da54ac7e274e9d/91860d21-01d7-4f3e-b7a6-b5d1ba84676b)
2. the ui needs to be worked on: the pop-up can become bigger so no scrolling needed
![image.png](https://images.zenhubusercontent.com/60f71f99b9da54ac7e274e9d/8db1eeec-0986-4bd2-bff4-1a3376d091f0)
3. The UI is not user friendly for the payment page (add your card have to be mandatory field) - when I don't add any card and tick the two check boxes and click confirm nothing happens, it should be mandatory and communicate as mandatory to the user:
![image.png](https://images.zenhubusercontent.com/60f71f99b9da54ac7e274e9d/a4872fab-5e65-42ed-8f24-49eb1a58c122)
4. I cannot add multiple cards : I added the first card, then added the second card info in the following section, but it is not added:
![image.png](https://images.zenhubusercontent.com/60f71f99b9da54ac7e274e9d/de6de0dd-25ed-4591-bedf-a20c53bed26d)
5. I am getting this error:
![image.png](https://images.zenhubusercontent.com/60f71f99b9da54ac7e274e9d/826e731d-3922-43ba-b2f5-42e886db8e2f)
I also tried again it gives me the same error:
![image.png](https://images.zenhubusercontent.com/60f71f99b9da54ac7e274e9d/909d7c55-36d9-4df0-aee8-3da08cfc3d2d)

**Comment by MoeNick** [comment]
@DonnaOftadeh Jan
Seems all of them are ux problems, did you have any functional problems as well?

**Comment by DonnaOftadeh** [comment]
@MoeNick @mateodaza both number 4 and 5 are functional issues, I cannot add another card to my account although the option is there and it seems working fine but it does not, at the last step it will not be added, also on number 5 I got the KYC error that I didn't pass one of the steps (I did all of the steps as said )

**Comment by DonnaOftadeh** [comment]
@MoeNick @mateodaza guys I want to test this but it gives me an error, can you please help to figure out where is the KYC problem, I did all of the steps as stated, but it seems there is something wrong, please help ASAP as we want to issue our next version and transak is a important feature, Thanks

**Comment by mateodaza** [comment]
@DonnaOftadeh is the same error that you showd previously? I got luck doing a KYC from the UK instead of USA

**Comment by DonnaOftadeh** [comment]
@mateodaza oh, man!:(  I am using vpn! what is the possible solution then?

**Comment by mateodaza** [comment]
@DonnaOftadeh nonono you can lie with your info! - I'm not using VPN and I'm in Colombia. Just look up some address in UK and use it

**Comment by DonnaOftadeh** [comment]
@mateodaza ok sure :)

**Comment by DonnaOftadeh** [comment]
@mateodaza @MoeNick @divine-comedian  I tried to pass the KYC couple of times but haven't been able to successfully pass. I do exactly as stated in this issue but for some reason I don't get the sms verification section (?), I searched a US number in the internet and paste it but no SMS verification step was appeared after entering the number, now says I have just passed one step of verification.

**Comment by mateodaza** [comment]
I think I skipped that verification using only email. Please do the KYC with UK instead of US. That's what worked for me @DonnaOftadeh

**Comment by divine-comedian** [comment]
tried making a payment from the UK - 
![image](https://user-images.githubusercontent.com/67759413/143931816-8f01dfbc-fbc2-4719-9b35-1ed876f17e75.png)

what do?

**Comment by divine-comedian** [comment]
testing on `next.giveth.io` 

using the card details for the UK I set an appropriate KYC - from manchester - and I successfully make a donation in DAI using transak - the DAI donation shows up on both my donations and the project's page

![image](https://user-images.githubusercontent.com/67759413/143932490-58ee3ee7-2a1f-4253-99cf-738ea4138924.png)
