### ISSUE TITLE
Cancelled projects are showing up in the projects list

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#31]
On live with chrome and metamask

It seems that cancelled projects are showing up in the projects list
![image](https://user-images.githubusercontent.com/74267818/120560970-f961b780-c3c0-11eb-8fc1-71c22ba6c6a5.png)

But when I navigate to the project page, I get htis:
![image](https://user-images.githubusercontent.com/74267818/120560993-02eb1f80-c3c1-11eb-9093-49351c9d5b9e.png)

**Comment by mateodaza** [comment]
So this is a super mega weird case, there are two 'my-perfect-project' both are James's. Here derives a problem that is we can't have two projects with the same slug.

The one being shown in the list is currently active and the other one seeing on project view is delisted (note they have different descriptions)

I believe James solved this and there's a condition now so double slugs don't happen again - I'll mark both projects as delisted as the front-end is handling this differentiation properly

**Comment by laurenluz** [comment]
made a new "my perfect project" and it has a unique slug (it has a "1" at the end)

however... the new "my perfect project is not showing up on the projects page when I search. I'm only seeing the old one from James

I will make a new issue for this as I think it is separate. let's call this one "done"

![image](https://user-images.githubusercontent.com/75490971/122273152-591a9100-ce9e-11eb-8331-af8e45a69dd4.png)
