### ISSUE TITLE
projectByAddress should be case-insensitive

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-next#311]
OnboardJS gives the user address in lowercase format but back-end is case-sensitive that makes problem.

This route:
projectByAddress(address: $address)

It's a blocker for #270 

@mohammadranjbarz Can you make it case-insensitive?

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
This is merged and deployed on `UAT`
you can test it with this query in https://serve.giveth.io/graphql

```
query{
  projectByAddress(address:yourWalletAddress){
    title,
    description,
    slug,
    walletAddress
  }
}
```
and change yourWalletAddress to lowercase you should get the result after the change too

@RamRamez 
This was your blocker, just wanted to inform you
