### ISSUE TITLE
Donation not showing up in "my donations" or on the project

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#32]
I just donated 20xDai (on May 31) to Bridging Digital Communities via main.next.giveth and the funds left my wallet, but they don't show up in "my donations"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/188a4391-5898-45c5-ad68-7eb48981e1d7)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c040181f-c273-4918-97dd-3752c868bc98)

**Comment by mateodaza** [comment]
Can we close this?

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/124015027-76bd1f80-d9a1-11eb-94ad-5c376f2840db.png)

**Comment by mateodaza** [comment]
I'm sorry to tell you that I have to manually add it, the donation passed but it wasn't saved because of an error I fixed just last week. do you still have the tx? and I'll manually add it

**Comment by laurenluz** [comment]
hmmm no I don't have it anymore. no worries! I'll close the issue :)
