### ISSUE TITLE
Deactivate project not working properly

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#33]
testing on next with brave

when I deactivate my project, the button changes, like so:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/14ae6ed9-5448-4807-8880-d2b20e25c966)

but then it is still active and visible/searchable from the projects page
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d362e31f-18c5-498f-8c00-9dbf6342d130)

**Comment by mateodaza** [comment]
same as #31 closing
