### ISSUE TITLE
Rich Text Editor: Emojis don't work properly

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#34]
I can't add hearts-for-eyes!! @mateodaza 

Or any emoji, really. the emoji pop-ups appear, but when I select them, it doesn't add. Testing on next with brave

before selecting
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c0c555b7-5441-4717-b660-a61acb4ef43e)

after selecting
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/3f5de883-2de2-4368-acde-0944a2c42862)

**Comment by mateodaza** [comment]
already live
