### ISSUE TITLE
Data Base Back-up Routine

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#341]

**Comment by mohammadranjbarz** [comment]
@geleeroyale 
Mateo said that we have regular backup of production DB (for impact-graph ), is it reliable?
and when it get backups from our DB?

**Comment by geleeroyale** [comment]
We back up the whole server with digitalocean - They are scheduled to start weekly Friday 9 PM to Saturday 8 PM (CET)

**Comment by mohammadranjbarz** [comment]
> We back up the whole server with digitalocean - They are scheduled to start weekly Friday 9 PM to Saturday 
8 PM (CET)

Thanks Kay

@MoeNick What do you think?
I think it can be sufficient for now

**Comment by MoeNick** [comment]
Yeah thanks
