### ISSUE TITLE
`My Projects` button while viewing project is dead

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-next#350]
on `next.giveth.io`

brave browser

while in the editing view of one of my projects I try to click the <- My Projects button at the top left of the page. However nothing happens when I click this element.

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/be754292-ff4d-40bc-9286-0fc24890f01e)

I'd like to take a crack at this one!

**Comment by mohammadranjbarz** [comment]
@divine-comedian It's on staging and ready for test

**Comment by divine-comedian** [comment]
testing `next.giveth.io` 

trying again the `my projects` button and it successfully takes me back to the `my projects` page. 

nice work!
