### ISSUE TITLE
Overlapping text on donate page 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-next#358]
using brave browser
`next.giveth.io`

on the donate page there's some text on the successful donation view that overlaps with the dropdown when you highlight `Projects` from the navbar.  

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/bb4a0af2-a433-4af0-8de3-54611e52a0aa)

**Comment by mateodaza** [comment]
sneaky zIndex haha

**Comment by mateodaza** [comment]
This is fixed with the new header
