### ISSUE TITLE
while creating a project with random non-contract eth address and I receive a syntax error:

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#360]
while creating a project I enter my ethereum address (a random non-contract eth address) and I receive a syntax error: 
![image](https://user-images.githubusercontent.com/67759413/139595793-5144891d-e1b3-4e16-ac7b-1e646cd1d89d.png)

I also get the same issue while trying to change the eth address while editing a project. However I can edit my project successfully WITHOUT changing the eth address associated. 

@RamRamez  moving this back to in progress

_Originally posted by @divine-comedian in https://github.com/Giveth/giveth-next/issues/351#issuecomment-955765190_

**Comment by MoeNick** [comment]
Im confused... We just accept eth address still? @CarlosQ96 @mohammadranjbarz @mateodaza

**Comment by mateodaza** [comment]
> Im confused... We just accept eth address still? @CarlosQ96 @mohammadranjbarz @mateodaza

@divine-comedian mentioned it was solved on the other issue, can we close?

**Comment by mohammadranjbarz** [comment]
> Im confused... We just accept eth address still? @CarlosQ96 @mohammadranjbarz @mateodaza

@MoeNick  @divine-comedian you can close this, it is fixed now
check https://github.com/Giveth/giveth-next/issues/351#issuecomment-976569016

**Comment by divine-comedian** [comment]
yes! this is resolved for the other issue
