### ISSUE TITLE
Create a project -> ETH address -> cannot use the wallet address in my profile 

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/giveth-next#368]

**Comment by DonnaOftadeh** [comment]
![image.png](https://images.zenhubusercontent.com/60f71f99b9da54ac7e274e9d/26b22986-94f6-42f2-be94-288149dfa858)
The message is not clear, from what I understand, it seems to me that this section is optional : if I want I can choose another wallet address otherwise it uses my main wallet address

**Comment by MoeNick** [comment]
@mateodaza do you have any idea?
