### ISSUE TITLE
Project Verification type form - need a link to the main Giveth page or the whole form open in another page 

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/giveth-next#369]
As a project creator I wanted to copy and paste the link to my project and I had to open another page and go to my project for that

Also at the end that I submitted my project I want to go to my home page, but there is only a reload button and social media icons

**Comment by DonnaOftadeh** [comment]
@markoprljic just to mention the current UX issues I encountered in next FYI

**Comment by WhyldWanderer** [comment]
I think the best solution would be to have the form open in a new tab when a project owner clicks 'verify my project'.

This would allow them to navigate the site while filling out the form and once the application is submitted, they can easily close the tab.

**Comment by DonnaOftadeh** [comment]
@WhyldWanderer yep - I do agree! however it would be nice if we have back to project button at the end of the type form beside the reload it would be nice

**Comment by markoprljic** [comment]
@DonnaOftadeh Can you please share me the link so I can try it out first? Thanks.

**Comment by DonnaOftadeh** [comment]
@markoprljic sure - this is the link to project verification typeform :https://hlfkiwoiwhi.typeform.com/to/pXxk0HO5?typeform-source=next.giveth.io

**Comment by markoprljic** [comment]
Ashley is right, we should open in new tab. 
Ideally, we can add a link to Giveth.io at the end of the form. That's all.

Until we embed this within our website this is the workaround.

**Comment by WhyldWanderer** [comment]
I can add a link back to the Giveth homepage or a specific page but I dont think I can link the button to the specific project page since this varies depending on who is filling out the form and i dont think typeform has the cpability to detect where the person navigated from... i can look into it though.

**Comment by markoprljic** [comment]
@WhyldWanderer Did you add the link at the end of the Verification form? Can we close this issue?

**Comment by WhyldWanderer** [comment]
Yep!
