### ISSUE TITLE
When I am not connected it shows me two options: switch wallet , connect wallet

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/giveth-next#370]

**Comment by DonnaOftadeh** [comment]
![image.png](https://images.zenhubusercontent.com/60f71f99b9da54ac7e274e9d/e8842d66-1f79-4255-80ae-430e5466935e)
How come when I am not connected it asks me to switch wallet

**Comment by mateodaza** [comment]
This is fixed
