### ISSUE TITLE
Add GUSD to token list

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#374]
Please add GUSD - the gemini token to the list of tokens to donate on mainnet :) 

https://www.coingecko.com/en/coins/gemini-dollar

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/9e5c6aba-cd89-4286-a952-468e0a1fb4b8)

For context: We want to get GIV listed on Gemini when we launch, so that people can donate it to the Giving Block Projects, and so it is important we have GUSD on our token list for donations. Just had the call with the Gemini representative and this is an important action item for the GIVeconomy!

**Comment by MoeNick** [comment]
Roger that.
