### ISSUE TITLE
The sign in button is not user friendly

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/giveth-next#376]

**Comment by MoeNick** [comment]
Would u provide more information? did you mean sign in?

**Comment by DonnaOftadeh** [comment]
![image](https://user-images.githubusercontent.com/53400757/140300998-96ebebbe-05d0-45a9-b9aa-74560d72021c.png)
Detect the login button : the blue one on the bottom left

**Comment by DonnaOftadeh** [comment]
@MoeNick give me 1 sec man :)))

**Comment by MoeNick** [comment]
All of this issues are related to Torus wallet I  assumed. 
Appreciate if you can mention in somewhere in the title of issue pls.

**Comment by DonnaOftadeh** [comment]
No, this is not related to any wallet type, I am not connected to anything as it is shown from the screen shot

**Comment by DonnaOftadeh** [comment]
@markoprljic this is a ux issue

**Comment by markoprljic** [comment]
This issue will be fixed in the redesign, whatever the problem here (I assume two buttons that are confusing). IMO this issue can be closed.
