### ISSUE TITLE
Admin panel - it doesn't show recent projects for the last one week

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/giveth-next#379]

**Comment by DonnaOftadeh** [comment]
![image.png](https://images.zenhubusercontent.com/60f71f99b9da54ac7e274e9d/36ac9bdf-3b30-4b7f-96e9-dba6eab30905)
It doesn't show the projects since 28th of Oct

**Comment by mohammadranjbarz** [comment]
> ![image.png](https://camo.githubusercontent.com/077fd1e760b7be8ae3753d40a44c735b544b1a346fc2d1f4caef8aaf4f8296a8/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630663731663939623964613534616337653237346539642f33366163396264662d336233302d346237662d393665392d646261366561623330393035) It doesn't show the projects since 28th of Oct

@DonnaOftadeh 
Could you send links of the projects that you cant see in Admin bro?

**Comment by DonnaOftadeh** [comment]
I wasn't sure whether it was on staging or on the main server so I checked both:
https://next.giveth.io/project/test-0
and this is on Giveth:
https://giveth.io/project/test-donna

**Comment by DonnaOftadeh** [comment]
Surprisingly, I found it just now! Did anyone fix it? I tried several times during the past week it didn't work! Now it seems working!

**Comment by mohammadranjbarz** [comment]
> Surprisingly, I found it just now! Did anyone fix it? I tried several times during the past week it didn't work! Now it seems working!

No I think no ones working on this,
so if you see this error again please leave the link of project here
