### ISSUE TITLE
Footer Link: Donate to Giveth is a dead link!

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-next#385]
Got this:
![image](https://user-images.githubusercontent.com/39466970/140831190-ac1647c4-11be-4650-8981-0bd55ddaaaff.png)

when clicking this:
![image](https://user-images.githubusercontent.com/39466970/140831480-2abf4aa1-db54-42f3-8370-cff398cd3dc7.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
[duplicate](https://github.com/Giveth/giveth-next/issues/291)
