### ISSUE TITLE
As a visitor, I want o browse the projects, read about us, FAQ .... from the footer, it keeps asking me to sign in whenever I click on any item in the footer

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/giveth-next#386]

**Comment by mateodaza** [comment]
Relates to auth improvements @RamRamez is working on

**Comment by RamRamez** [comment]
Related to PR #465 
@DonnaOftadeh Please check it

**Comment by divine-comedian** [comment]
testing `next.giveth.io` 
brave browser

I do not receive any prompts to sign-in while navigating the items in the footer 
looks to be resolved!
