### ISSUE TITLE
Donation Amount being calculated wrong on xDAI

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#39]
I have no idea where these numbers are coming from. At first it was saying my thousands of xDai was worth less than $0.01... then after some refreshing/changing network, it was saying that my 0.01 xDai was worth $41.26

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/46cd8147-73fd-4ef3-8867-e46348a45b7c)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5bc16d59-5bfe-444d-a3c6-2fafc412129c)

**Comment by MerlinEgalite** [comment]
This is should be fixed I guess..

**Comment by laurenluz** [comment]
fixed 
![image](https://user-images.githubusercontent.com/75490971/121404420-2d852d00-c919-11eb-9a7e-e98816557cba.png)
