### ISSUE TITLE
Optimise menu when the user is signed in - My projects

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/giveth-next#392]

**Comment by DonnaOftadeh** [comment]
![image](https://user-images.githubusercontent.com/53400757/140886825-339715bd-8dba-4d0e-80d8-1296ff1f4e80.png)

When I am signed in, the top right menu under my account can be optimised:
We have three sections: My projects, create project and project verification that can all listed under My projects, and why we have create project on the menu -> we have one big button for creating a project next to my account and one in the menu which I think is redundant, also I don't know the purpose of project verification on the menu, I think it would be better to be able to verify a project from my project list, under each project - currently we have to enter a project to be able to verify a project:
![image](https://user-images.githubusercontent.com/53400757/140886989-d1755dba-a5b3-44e5-89f5-7f4945f165a1.png)

**Comment by markoprljic** [comment]
This is taken care of in the redesign. Closing it.
