### ISSUE TITLE
When I want to log in with my Gmail, behind the log in page the authorization message shows up

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/giveth-next#394]

**Comment by DonnaOftadeh** [comment]
![image](https://user-images.githubusercontent.com/53400757/140890919-0a6ede78-364d-4ecd-ab61-4566d73c7ae6.png)

**Comment by mateodaza** [comment]
Not sure if we can change this

**Comment by MoeNick** [comment]
Let's close it for now
