### ISSUE TITLE
There are some dots appeared on this project in the projects page 

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/giveth-next#399]

**Comment by DonnaOftadeh** [comment]
![image](https://user-images.githubusercontent.com/53400757/140899870-5b5533db-9f88-4b95-b55f-25b14393dbfe.png)
on the project "So boring" some dots weirdly appeared: may be because the Youtube link is currently down

**Comment by mateodaza** [comment]
removed formatting on cards, this is solved on staging now
