### ISSUE TITLE
Pan price is WRONG!!!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-next#40]
![Screen Shot 2021-05-07 at 12 52 10 PM](https://user-images.githubusercontent.com/14945613/117501598-8e1df480-af7e-11eb-8098-6bd992b5024a.png)

**Comment by MerlinEgalite** [comment]
The API we fetch token prices has not the $PAN token listed there so we need to change the API it seems... @mateodaza do you know another API that can be use to replace the current one https://www.cryptocompare.com/ ?

**Comment by geleeroyale** [comment]
If we need to switch the API we could directly use Uniswap - they have a subgraph so should be easy to integrate:

https://uniswap.org/docs/v2/API/overview/

**Comment by laurenluz** [comment]
can we please fix this soon? it's still wrong

![image](https://user-images.githubusercontent.com/75490971/122612344-33c58880-d040-11eb-924e-a8281c9c4602.png)

https://www.coingecko.com/en/coins/panvala-pan

**Comment by mateodaza** [comment]
I'm sorry, Merlin worked on this a while ago but there's a detail missing - I will push his update and then we can come back to it. I think on his branch the PAN token is priced properly

**Comment by laurenluz** [comment]
thanks Mateo - you are a winner 🏆

**Comment by divine-comedian** [comment]
PAN seems to be showing up at the correct price! 

![image](https://user-images.githubusercontent.com/67759413/124392182-3ec81c00-dcc2-11eb-81c8-e9bbb68d5bf2.png)
