### ISSUE TITLE
Getting error when running project locally

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-next#411]
![Screen Shot 1400-08-25 at 21.00.07.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/39112d1b-495f-4196-93ec-43173573c509)

I tested with `mteo-mig` branch
@RamRamez  @mateodaza  could you take a look on this?

**Comment by RamRamez** [comment]
I installed from scratch and it worked fine. maybe you are using wrong config or your internet provider is blocking the back-end.

**Comment by MoeNick** [comment]
Shall we keep it as it? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> Shall we keep it as it? @mohammadranjbarz

No it's ok, maybe it was from my end
you can close this
