### ISSUE TITLE
Progress bar on Create New Project flow has a bug

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-next#42]
## 📋 Anything to add?
Both on Staging and Production. I tried refreshing the page a few times but no luck. 
The progress bar does not show the correct section I find myself in the Create New Project flow.

![Image 2021-04-26 at 4.28.04 pm.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/81c1ea4e-efcf-451c-9050-8f625cd1c9ae)

![Image 2021-04-26 at 4.27.50 pm.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/0a0a7bf9-a4ca-4aef-99d5-028fa647e6f4)

**Comment by divine-comedian** [comment]
testing the project flow on `next.giveth.io`  - going through the flow there is project name, description, category, and ETH address - but there are many more things that we set during project creation like admin, location, image - are these supposed to show up as well? @mateodaza 

![image](https://user-images.githubusercontent.com/67759413/125653229-a90d85af-0613-4a13-826c-67844de786f3.png)

**Comment by MoeNick** [comment]
@mateodaza , mitch asked a question above that is my question too ;) 
@divine-comedian can u pls test again and approve it?

**Comment by divine-comedian** [comment]
Has there been any changes since my last test?

**Comment by MoeNick** [comment]
I don't think so.

**Comment by mateodaza** [comment]
> testing the project flow on `next.giveth.io` - going through the flow there is project name, description, category, and ETH address - but there are many more things that we set during project creation like admin, location, image - are these supposed to show up as well? @mateodaza
> 
> ![image](https://user-images.githubusercontent.com/67759413/125653229-a90d85af-0613-4a13-826c-67844de786f3.png)

They show up when you fill them, we could change the UI to always show the links on top but faded if they are not completed.

Also I think I'll remove the admin field, we do nothing with that value.

**Comment by MoeNick** [comment]
@mateodaza I think we have it for our last sprint . Do you have any updates? it in "in progress" in my zenhub board.

**Comment by laurenluz** [comment]
oh maaan - checked this on live, it's a little buggy still... when I start w a clean cache and go to create a project... only the "project name" title comes up
![image](https://user-images.githubusercontent.com/75490971/131897271-83121b43-2d8b-4a7a-a6c1-d78ab2036d69.png)

then when I go to the next one... "admin"... the rest of the titles show up
![image](https://user-images.githubusercontent.com/75490971/131897369-c08a9801-16f3-46af-b820-6b376f82c57e.png)

I also noticed something weird... if I don't fill out one field (i.e. admin) and go to the next page (description)... admin is still greyed out...
![image](https://user-images.githubusercontent.com/75490971/131897442-5359b97e-ccbe-4102-b958-8c0918870e0c.png)

but if I go back write something in admin... go forward... (admin becomes green) and then go back and delete what I wrote in the admin field.. and go forward again to project description... admin stays green...

![image](https://user-images.githubusercontent.com/75490971/131898283-fcdacf04-4533-42eb-b0a7-4cf48c5f0c89.png)

I think it would maybe be the easiest fix if we just made them green if you've passed that page and grey if you haven't got to it yet... maybe not fuss with having it recognize if something was typed or not.

**Comment by mateodaza** [comment]
lmk if it's better now

**Comment by laurenluz** [comment]
mateoforpresident - it's WAY better.. moving to done

![image](https://user-images.githubusercontent.com/75490971/131908814-6995440f-c559-4127-9b16-149c841e5033.png)
