### ISSUE TITLE
Like feature on homepage & projects full page isn't working

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#421]
Related to #381

When I click the heart, nothing happens.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0f380d80-c966-4ba8-9c16-13aba92f7301)

**Comment by mateodaza** [comment]
closing because of duplicate [#381 ](https://github.com/Giveth/giveth-next/issues/381)
