### ISSUE TITLE
banner images are missing from projects

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-next#447]
projects old and new now just have GIVETH for the banner...
![image](https://user-images.githubusercontent.com/39466970/144717790-c0ba13de-afaf-4f11-9935-5e4e785fda08.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by MoeNick** [comment]
Would u pls take a look @mateodaza

**Comment by mateodaza** [comment]
This is the actual project, the slug was changed https://giveth.io/project/The-Wellness-Bus-0

![image](https://user-images.githubusercontent.com/18689480/145682417-72e70320-da08-4a5d-bc0e-f9906863739c.png)
