### ISSUE TITLE
Wrong URL on autopilot

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-next#451]
Autopilot mail is pointing to a wrong URL (`View my project` button)

[https://giveth.io/project/%7B%7B%20person.slug%20%7D%7D%C2%A0?utm_campaign=project+3+month+Check+Up+NEW+Giveth+2.0&utm_medium=email&utm_source=autopilot](https://giveth.io/project/%7B%7B%20person.slug%20%7D%7D%C2%A0?utm_campaign=project+3+month+Check+Up+NEW+Giveth+2.0&utm_medium=email&utm_source=autopilot)

![image](https://user-images.githubusercontent.com/73441857/145190443-6d0e1a28-d6cd-4bca-8800-e6c202d3b072.png)

**Comment by WhyldWanderer** [comment]
@RamRamez was this from a project that you created on staging? or on production?

**Comment by RamRamez** [comment]
> @RamRamez was this from a project that you created on staging? or on production?

From the account name "Ram MetaMask", I noticed that it was on staging.

**Comment by WhyldWanderer** [comment]
okay thats why... if it's a project on staging its using the staging project slug and sending you to production

**Comment by RamRamez** [comment]
but it's not sending to a project slug. There is no project slug in the link.

This is the link on "View my project":

![image](https://user-images.githubusercontent.com/73441857/146636238-411e5905-c33b-4a32-8e42-47144afbcf46.png)

**Comment by divine-comedian** [comment]
on autopilot I can test this feature by sending a test email - it will fill in personalized data with a random or specified contact we have stored in autopilot 

![image](https://user-images.githubusercontent.com/67759413/146855037-5f4fa08c-1cd8-41ee-8a2d-9d9a793386c4.png)

I sent myself a test email using a user profile of a known project on giveth.io 

![image](https://user-images.githubusercontent.com/67759413/146855113-532782ad-ad13-42f9-ad36-398bf423bf24.png)

I click the view my project link and it successfully redirects me to the associated project on giveth.io (production) 

![image](https://user-images.githubusercontent.com/67759413/146855220-bcca6e35-fc6a-47cc-a56b-b8b2890be33d.png)

**Comment by divine-comedian** [comment]
@RamRamez  I can't seem to reproduce the error

**Comment by divine-comedian** [comment]
We found the issue, hopefully, it seems it was a problem with autopilot appending UTM tags onto our emails, they have since been removed - we tested this and the issue seems to be resolved.

**Comment by RamRamez** [comment]
@divine-comedian 
All emails from Autopilot to me is pointing to a single project ([this one](https://giveth.io/project/greensteps%C2%A0)) that is not mine

![image](https://user-images.githubusercontent.com/73441857/148588420-9df65f74-19be-404f-be2c-67fde2cbff2f.png)

**Comment by WhyldWanderer** [comment]
@RamRamez what is the email address where you are receiving these emails? And what is your project name?

**Comment by divine-comedian** [comment]
I talked to Ramin and he said he wasn't sure if this was resulting from staging or production - we've identified that the autopilot slugs will not work properly for projects only on staging. 

I can't seem to reproduce this error.
