### ISSUE TITLE
Sign-in and meta mask is connected- back to homepage, showed connect your wallet. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#457]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/fc70734c-583d-4ab5-b60a-77d18bb8925e)

**Comment by RamRamez** [comment]
Related to PR #465 
@MoeNick Please check it

**Comment by divine-comedian** [comment]
testing `next.giveth.io` 

I tried navigating around to a few different pages .. /projects, /about /join and then going back to the homepage - my wallet remained signed in and nothing change in my sign in status during any navigations throughout the DApp 

this looks to be resolved!
