### ISSUE TITLE
I have double menu or header in my account

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#469]
With the new  header we can remove the old menu.

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/c9ddcd7c-2a68-4cea-9ed0-2da7667f44d8)

**Comment by RamRamez** [comment]
Resolved in PR #474

**Comment by divine-comedian** [comment]
testing `next.giveth.io` 
old menu is gone! 

the new header and drop down menu looks great! 
![image](https://user-images.githubusercontent.com/67759413/146223521-24bdf2f6-0845-4781-bda5-4f2d479a7ffc.png)
