### ISSUE TITLE
I need to see my connected wallet if I have an account

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#470]
As a user, If I have an account after I signed in, I need to see my address somewhere:

![image](https://user-images.githubusercontent.com/80677512/145815260-c5767990-56dd-463a-be28-4006c31c86db.png)

**Comment by MoeNick** [comment]
@markoprljic do you have any idea?

**Comment by markoprljic** [comment]
We show wallet address under Wallet.

![Image 2021-12-13 at 3 36 16 pm](https://user-images.githubusercontent.com/5704285/145831573-743ffe2f-b068-445f-9a71-2f22a8bb0bc0.jpg)

**Comment by MoeNick** [comment]
Thanks @markoprljic 
@RamRamez can u pls take this issue, it's a bug.

**Comment by RamRamez** [comment]
Resolved in PR #475 
@MoeNick Please check it

**Comment by divine-comedian** [comment]
testing `next.giveth.io` 

checking out the new drop down menu I am a user connected and have a profile - the drop down menu shows me the abbreviated ethereum address that I am currently using. 
![image](https://user-images.githubusercontent.com/67759413/146223290-a04a4776-a9ee-4388-ad7d-1b248365de70.png)
 looks to be resolved!
