### ISSUE TITLE
I have a not-connected address, but it shows me sign-in instead of connect. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#471]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/e792d920-5c42-410a-a7a2-a47dac3f4d02)

**Comment by RamRamez** [comment]
@MoeNick Yeah, that MetaMask account is not connected, but one of your other MetaMask accounts are connected and the App will connect through that one.

**Comment by divine-comedian** [comment]
can we move this issue? looks to be a testing error -
