### ISSUE TITLE
In the header, "Community" should be "Join"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#479]
This links to giveth.io/join ... should be called "Join" as it is in the previous version

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ff2b7a66-f7eb-4d41-924d-a3d701fe5e8f)

**Comment by MoeNick** [comment]
I think @markoprljic said to change it to Community in design channel.

**Comment by RamRamez** [comment]
@MoeNick Should I change it or it still needs clarification?

**Comment by MoeNick** [comment]
Hold on pls.

**Comment by markoprljic** [comment]
Please change it to Community @RamRamez

**Comment by MoeNick** [comment]
@laurenluz before closing this issue, pls consider we have to change it in GivEconomy too.

**Comment by laurenluz** [comment]
@markoprljic We changed it from "Community" to "Join" on the DApp due to user feedback and comms discussion. It should be "Join".

The page links to "giveth.io/join"

The page is called "Join our Community"

The header should say "Join"

**Comment by MoeNick** [comment]
@RamRamez sorry for double work, pls change it.

**Comment by markoprljic** [comment]
> @markoprljic We changed it from "Community" to "Join" on the DApp due to user feedback and comms discussion. It should be "Join".
> 
> The page links to "giveth.io/join"
> 
> The page is called "Join our Community"
> 
> The header should say "Join"

I'm wondering what the user feedback was and arguments during the comms discussion?

I believe that the term Join can be misleading and make users think this is where they register an account for Giveth.

Also, the content on that page is all about Community and the term in the main navigation does not reflect what is actually on that page.

Finally, it's one more emphasized call to action in the main navigation fighting for attention next to Create a project and/or Sign in.

I respectfully disagree with the decision to rename it to Join. I would like to be proven wrong with user tests and analytics. Although, it's not the first world problem and it would be better to use our resources to do user testing on more important things at the moment.

**Comment by MoeNick** [comment]
@markoprljic 
It's so admirable that you say your opinions professionally and it could be more professional to consider this fact that we dont have ANY   user behavior testing and analytics, what we have done so far was based on these common feedbacks that we have from comms cause they face the clients (users) more than us.

**Comment by laurenluz** [comment]
What we have is feedback from users like Mia who join Giveth and try to orient themselves, but are not deep in the weeds.

It was her feedback that sparked this conversation months ago when we changed it from community to join.

But whatever.. leave it as communtiy then, it's not critical and we can change it later if people give us more of the same feedback we got before.
