### ISSUE TITLE
GIVbacks eligibility badges design

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-next#48]

**Comment by markoprljic** [comment]
On the floating info box
![Image 2021-06-09 at 4 25 57 pm](https://user-images.githubusercontent.com/5704285/121373497-6801c080-c93f-11eb-889f-a71b1156aa78.jpg)

**Comment by willyogo** [comment]
On the card, instead of "GIVBACK APPLY" can we say "ELIGIBLE FOR GIVBACKS," "DONATE AND EARN GIV," "EARN GIV," or "EARN GIVBACKS" ? Open to other copy suggestions too

**Comment by willyogo** [comment]
@WhyldWanderer @laurenluz @divine-comedian can comms team suggest some copy for both the top-level statements and also the tooltip? I think tooltip should include a "Learn more" link to the GIVbacks blog post too

![image](https://user-images.githubusercontent.com/26232238/121378775-b8a5f900-c900-11eb-9221-a358e0890e80.png)

**Comment by WhyldWanderer** [comment]
> On the card, instead of "GIVBACK APPLY" can we say "ELIGIBLE FOR GIVBACKS," "DONATE AND EARN GIV," "EARN GIV," or "EARN GIVBACKS" ? Open to other copy suggestions too

I like your suggestions Willy!... 
Could also say "VERIFIED PROJECT" and when you hover over the badge or the words you would get a tool tip stating "When you donate to this project, you will be able to claim up to 75% of your donation amount in GIV tokens."

**Comment by WhyldWanderer** [comment]
> @WhyldWanderer @laurenluz @divine-comedian can comms team suggest some copy for both the top-level statements and also the tooltip? I think tooltip should include a "Learn more" link to the GIVbacks blog post too
> 
> ![image](https://user-images.githubusercontent.com/26232238/121378775-b8a5f900-c900-11eb-9221-a358e0890e80.png)

Where will this wording be positioned?

**Comment by WhyldWanderer** [comment]
Maybe this text can be useful in one of these areas
"Giveth is integrating a revolutionary concept into our donation platform! We want to reward those who choose to give to verified projects that they believe in. From this day forward, when you make a donation to a project with a verified badge on Giveth.io, you will be issued GIVbacks in the form of GIV tokens. Learn more 'here'." or something like that. .. 

idk... it might be too long lol

**Comment by markoprljic** [comment]
> Maybe this text can be useful in one of these areas
> "Giveth is integrating a revolutionary concept into our donation platform! We want to reward those who choose to give to verified projects that they believe in. From this day forward, when you make a donation to a project with a verified badge on Giveth.io, you will be issued GIVbacks in the form of GIV tokens. Learn more 'here'." or something like that. ..
> 
> idk... it might be too long lol

This is good for a popup.

**Comment by mateodaza** [comment]
> This is good for a popup.

@markoprljic  Do we have a design for this already man? I came up with this while I do the general redesign of the floating box

![image](https://user-images.githubusercontent.com/18689480/123327328-ec3b7280-d4ff-11eb-9572-28c321d1bb4b.png)

The idea is to show the popup when clicked on 'verified'

**Comment by markoprljic** [comment]
Keep it for now until we do other redesigns of the project page.

**Comment by MoeNick** [comment]
@markoprljic any updates on this issue? 
I think we can put more priority on token integration stuff. we planned to start it after two weeks from on.

**Comment by markoprljic** [comment]
See above https://github.com/Giveth/giveth-next/issues/48#issuecomment-867927421
