### ISSUE TITLE
add drop down menu for non-signed in users 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-next#486]
currently the only way to switch wallet provider is to sign-in with the currently cached wallet provider then click `change wallet` 

one solution we proposed was to have the regular drop down menu appear which allows the user to change wallet without having to sign-in, clicking anyother button except for `change wallet` will prompt the user to sign in with the current wallet provider

**Comment by MoeNick** [comment]
I was thinking of this flow:
![Slide1.JPG](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/d9fb2ec1-bfd6-4a70-8f04-e425086145b9)
![Slide2.JPG](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/7b3afb61-80a1-48c4-83db-47a3d88030e2)
![Slide3.JPG](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/8b9e8d50-01ef-4f43-ac88-f9e4b7baa91e)
![Slide4.JPG](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/5d7ed11d-a280-4d86-9806-aad1abce539f)
![Slide5.JPG](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/9263af85-e720-4069-8ece-d6bd0c11218c)
![Slide6.JPG](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/c7b933d4-6f31-4f1b-90d2-e8a7747946b1)

**Comment by divine-comedian** [comment]
@MoeNick  this flow looks good!

**Comment by MoeNick** [comment]
@markoprljic would you pls confirm for nextjs version?

**Comment by markoprljic** [comment]
The drop-down should overlay the rewards button.

**Comment by MoeNick** [comment]
@RamRamez 
The final flow is this: 
https://whimsical.com/giveth-SLPFhtNjpD4G4L84cLF2jD

**Comment by MoeNick** [comment]
Questions  just to keep the record of it:
1- Sign Out should be hidden before sign-in? and be appear after the user signs the address with his wallet? 
2- We can't disconnect the app from wallet, but we only can invalidate the sign token form the app. so what behavior do you except after sign out? shout it be the state that user see the sign modal? or it should get back to SIN IN button from the header?
3- We kinda blocked by new Sign In modal in Figma, I think @Mo 🤖 is pushing to finalize it right now.

**Comment by divine-comedian** [comment]
1. - Yes 
2. - When user signs-out it should show the initial state before sign-in - is it possible to return the user to this state?
![image](https://user-images.githubusercontent.com/67759413/146189000-b47e8eba-8762-4e6b-9b07-04bd22a97971.png)

**Comment by markoprljic** [comment]
@divine-comedian Here's a demo https://www.figma.com/proto/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?page-id=2354%3A78970&node-id=2981%3A83718&viewport=380%2C48%2C0.14&scaling=min-zoom&starting-point-node-id=2981%3A83718

@MoeNick This is how the flow should be.

**Comment by divine-comedian** [comment]
@markoprljic  there's just one state that's missing from the figma - its the user who has a profile and a wallet connected - normally if they have a profile we would show them their username instead of their ethereum address?

**Comment by markoprljic** [comment]
Of course we do. It will be like that.

**Comment by MoeNick** [comment]
> Of course we do. It will be like that.

Im a little bit confused, we cant do it for Laurens version for sure, Is it desired flow for typescript version?

And what about https://whimsical.com/giveth-SLPFhtNjpD4G4L84cLF2jD ? is it finalized or not? 
@markoprljic

**Comment by markoprljic** [comment]
> Im a little bit confused, we cant do it for Laurens version for sure, Is it desired flow for typescript version?
Yes.
> And what about https://whimsical.com/giveth-SLPFhtNjpD4G4L84cLF2jD ? is it finalized or not? 
Yes.

**Comment by divine-comedian** [comment]
@RamRamez  which parts of this issue can be tested? sorry the title is confusing - I'm not sure what to check in the drop-down menu now 

and is it on `next.giveth.io` or `typescript.giveth.io`?

**Comment by RamRamez** [comment]
@divine-comedian It's on `next.giveth.io`

When user wallet is not connected, user should see just `SIGN IN` on menu bar.
When wallet is connected but user has not yet signed the message with his wallet, should see the user details menu on hover (without `sign out` option)
When user signs the message, he see user details menu on hover (with `sign out` option)

If user is registered, he see his name on main menu, if not, he see his wallet address.

**Comment by divine-comedian** [comment]
okay thank you for explaining it in a bit more detail. 

I went through the drop down menu flow -

on a fresh load totally signed out there is no drop down menu 
when I log into my wallet my profile name, and wallet address show up but there is no option to sign out
once I sign the message I can see an option to sign out

looks to be working as described!  - moving to DONE
