### ISSUE TITLE
The drop-down should overlay the rewards button.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#490]
The drop-down should overlay the rewards button.

_Originally posted by @markoprljic in https://github.com/Giveth/giveth-next/issues/486#issuecomment-993623619_

**Comment by RamRamez** [comment]
Resolved in PR #494

**Comment by divine-comedian** [comment]
the drop-down menu now overlaps on top of the GIV token counter 
![image](https://user-images.githubusercontent.com/67759413/146221218-f10afef9-4bec-403a-93a6-bd59ba305828.png)

I think this was the issue? looks to be resolved.
