### ISSUE TITLE
Change SIGN-IN function to select wallet instead of check wallet

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#495]
It prevents this bug: If I select a wallet and couldn't make it connected, clicking on Sign-In let me choose another wallet and Im continue with the new wallet.

**Comment by RamRamez** [comment]
Resolved in PR #496

**Comment by divine-comedian** [comment]
testing `next.giveth.io` 

on first load - 
![image](https://user-images.githubusercontent.com/67759413/146220686-b9726809-e8e2-4940-92da-775e99c67967.png)

this opens onboardJS then once I select my wallet I can sign in with the chosen wallet
