### ISSUE TITLE
FAQ - we should change the tax deductible question answer to something that convey that when we get people tokens it looses its tax deduction status (probably!)

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/giveth-next#509]

**Comment by DonnaOftadeh** [comment]
![image](https://user-images.githubusercontent.com/53400757/146217187-57f523c7-2338-4bc2-9ed0-db757463ae1d.png)

**Comment by MoeNick** [comment]
@divine-comedian can u pls take it?

**Comment by WhyldWanderer** [comment]
I can change this!

**Comment by divine-comedian** [comment]
text looks to be updated - good enough for now until we can get a full legal review 
![image](https://user-images.githubusercontent.com/67759413/147588615-89193505-8508-454f-824e-37239e7d8e10.png)

moving this to DONE
