### ISSUE TITLE
Hero display problem on Safari

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#518]
## 📋 Anything to add?

Everything else looks fine! Except the hero is fleeing to the left ...

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/317685/146274021-b8e6ca40-ffde-4c3e-a9ea-54302a714f90.png">

## ⏰ Urgency/Deadline/Blockers?
🚨

**Comment by mateodaza** [comment]
closing because stale
