### ISSUE TITLE
Creating Project Error

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#521]
**Please describe the issue or bug you are experiencing:**
Something went wrong - creating project
![image](https://api.typeform.com/responses/files/4ce85dec6a96845ec82173d54b47f5bb627d5924be653bba03c3b999cf112895/Screenshot_2021_12_16_192236.jpg)

**Comment by mateodaza** [comment]
Yesterday I created an issue for this.[Duplicate](https://github.com/Giveth/giveth-next/issues/517)
