### ISSUE TITLE
GitCoin Grants round is over - we should remove the banner

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#531]
GitCoin Grants round is over - we should remove the banner

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/5096835e-4148-47d7-aba5-1333e51f154a)

**Comment by mateodaza** [comment]
It'll be gone when it stops being 16th everywhere in the world :)

I'll let that happen instead of pushing to live only for that
