### ISSUE TITLE
Donating Anonymously - tax donation receipt?

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#535]
As far as Im aware, "Giveth does not support donors in obtaining tax deductions and if a donor receives GIVbacks for donating to a verified project, we can not guarantee that the donation is legally tax deductible." - As stated in terms of use

So this text is misleading:
We should remove the hover tooltip

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/5072f304-e5b1-4e91-b834-b1914f1c0f58)

**Comment by divine-comedian** [comment]
testing `next.giveth.io` 

tooltip - GONE! 

looks to be resolved
