### ISSUE TITLE
Donating on xDai - Network fee hover tooltip

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#536]
When donating on  the xDai chain, the "Network Fee" hover tool tip says Ethereum blockchain
This should say xDai Network
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/cceb9329-f06c-41bc-a6e3-8c8e1b611023)

**Comment by divine-comedian** [comment]
I noticed the tooltip text didn't exactly match so I made some changes into a local commit - 
https://github.com/Giveth/giveth-next/tree/mitch-tooltipFix-1

**Comment by divine-comedian** [comment]
merged in PR - https://github.com/Giveth/giveth-next/pull/541
