### ISSUE TITLE
Add tooltip to "GIV currently in wallet"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#538]
Hey Dapp friends,

@geleeroyale made this issue: https://github.com/Giveth/GIVeconomy/issues/312

But he meant it for you guys... In GIVeconomy right now, this is a hover tooltip... See it here: https://liquidity-mining-dapp.vercel.app/

It would be good if they behaved the same across everything, so please just add a tool tip for Lauren's version. I know this will be a cool dropdown later

**Comment by mateodaza** [comment]
Gotchaaaa, we can transfer that issue to here also. I'll do that
