### ISSUE TITLE
Add Project categories

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-next#55]
As a user I want to be guided through the process of finding the projects that are of interest to me. 

We discussed a **mega drop down** on the hover of the projects link.
Other options:

- Single page similar to Causes but for Categories
- Somewhere on the homepage top 3 categories + link to see all
- footer list all categories (good for SEO)

**Comment by laurenluz** [comment]
This is done, as expected... but my person opinion is that the enormous dropdown is a bit clunky - maybe we can make it a bit smaller? @mateodaza 

![image](https://user-images.githubusercontent.com/75490971/128639577-e3a68b04-8023-441d-ae91-8a1b57df15ea.png)
