### ISSUE TITLE
When pasting in a token address to donate, the amount in wallet is wrong

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-next#556]
## 📋 Anything to add?
![Screen Shot 2021-12-17 at 2 17 54 PM](https://user-images.githubusercontent.com/14945613/146603061-f4b2d911-44f2-4d9a-abb9-3b292b072e50.png)

The dapp says i have a flat 170,000... but i got 36,464 DR GIV....

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mateodaza** [comment]
The token in the dApp is the previous token to DRGIV. I have to update that

**Comment by mateodaza** [comment]
this is done
