### ISSUE TITLE
Staging: I can't see my address in the header

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#559]
Its happening on next.giveth.io

If I don't have a completed account, I can't see my address in the header.
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/082ac64f-1d5c-41c0-b7c6-f4f4db51fd53)

**Comment by mateodaza** [comment]
Which network are you in?

**Comment by MoeNick** [comment]
xDai as you can see in screenshot, bbut it didn't update when I changed the network.
