### ISSUE TITLE
Rich text support for project descriptions

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-next#56]
## 📋 Anything to add?
Users should be able to add basic styles to their text (bold, sizes, etc)

## ⏰ Urgency/Deadline/Blockers?
After MVP

**Comment by laurenluz** [comment]
I think this was still in "staging" because all my wishes had not yet been granted 🤣

**Comment by laurenluz** [comment]
Project description is still a lil' small. No tooltips on formatting things. And no right/middle/left justification. I don't think these things are necessarily urgent though and would be alright to close this issue for now.

Underlined hyperlinks is happening which is awesome
![image](https://user-images.githubusercontent.com/75490971/122268696-a1838000-ce99-11eb-8660-6e98ab7e5e94.png)
