### ISSUE TITLE
What Pan are we talking here? - Deal with coins that hae the same ticker symbol

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-next#57]
<img width="417" alt="Screen Shot 2021-04-14 at 8 37 45 AM" src="https://user-images.githubusercontent.com/14945613/114738369-30fc9d80-9d48-11eb-93e7-f4232c331155.png">

https://www.coingecko.com/en/coins/pantos
28 cents
vs

https://www.coingecko.com/en/coins/panvala-pan
11 cents

**Comment by divine-comedian** [comment]
PAN seems to be showing up at the correct price! 

![image](https://user-images.githubusercontent.com/67759413/124392182-3ec81c00-dcc2-11eb-81c8-e9bbb68d5bf2.png)


most of the logos show up correctly with the exception of tokens that don't have unique ticker symbols, when we choose those tokens on the UI it shows up with whatever ticker symbol that was previous.

Both on Ropsten and xDAI

![image](https://user-images.githubusercontent.com/67759413/124392212-57d0cd00-dcc2-11eb-9545-6ac38ccc5c74.png)

![image](https://user-images.githubusercontent.com/67759413/124392254-8189f400-dcc2-11eb-8b7e-9ec657553fe0.png)

**Comment by mateodaza** [comment]
Nice catch, will fix this. Thanks man

**Comment by MoeNick** [comment]
@divine-comedian would you please confirm it's done?

**Comment by divine-comedian** [comment]
looks to be fixed! tested on xDAI and mainnet.

![image](https://user-images.githubusercontent.com/67759413/124921477-725abd00-dfc6-11eb-8d49-9e36cfa57e4e.png)

![image](https://user-images.githubusercontent.com/67759413/124921673-a33af200-dfc6-11eb-8067-6bdd62b6b259.png)
