### ISSUE TITLE
Update project verification typeform links

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#581]
The project verification application link has changed. We need to update this on the DApp

Old link: https://hlfkiwoiwhi.typeform.com/to/pXxk0HO5

New link: https://giveth.typeform.com/verification

- [x] My account

- [x] Project page

I think these are the only places where it is linked to the DApp

**Comment by divine-comedian** [comment]
I checked both cases including while viewing a project that I own as well as the project creation high five page - 

both had the aforementioned updated link.

moving to DONE!
