### ISSUE TITLE
something went wrong while adding your project - failed to fetch

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#591]
**Please describe the issue or bug you are experiencing:**
'something went wrong while adding your project - failed to fetch'
![image](https://api.typeform.com/responses/files/e29470ba3144d76b9a875ab4135f52727a884ade490a4c63019e01d51d980c84/Screenshot_2021_12_24_12.37.35_PM.png)

**Comment by mateodaza** [comment]
closing as we can't replicate anymore and I think it's working fine
