### ISSUE TITLE
xDai onchain fee showing ETH dollar value

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-next#596]
![Screen Shot 2021-12-26 at 11 50 35 AM](https://user-images.githubusercontent.com/14945613/147416176-bd2b1b86-035a-45d8-8084-71b577691a59.png)

**Comment by GriffGreen** [comment]
https://github.com/Giveth/giveth-gatsby/issues/913

**Comment by MoeNick** [comment]
@aminlatifi I mention you here, you have ideas changing the setting of gas in metamask also

**Comment by aminlatifi** [comment]
> @aminlatifi I mention you here, you have ideas changing the setting of gas in metamask also

It's so easy. Pass this data as the last parameter of function which makes the tx, it edits the gas setting

https://github.com/Giveth/liquidity-mining-dapp/blob/5168d74fb6c79189684922c93134ff57b81dab54/src/config/production.ts#L90

**Comment by mateodaza** [comment]
> > @aminlatifi I mention you here, you have ideas changing the setting of gas in metamask also
> 
> It's so easy. Pass this data as the last parameter of function which makes the tx, it edits the gas setting
> 
> https://github.com/Giveth/liquidity-mining-dapp/blob/5168d74fb6c79189684922c93134ff57b81dab54/src/config/production.ts#L90
> 
> Like this:
> 
> ```
> return await lmContract
> 			.connect(signer.connectUnchecked())
> 			.stakeWithPermit(
> 				ethers.BigNumber.from(amount),
> 				rawPermitCall.data,
> 				{
> 					gasLimit: 300_000,
> 					...gasPreference,
> 				},
> 			);
> 			```
> ```

Gonna make this a separate issue
