### ISSUE TITLE
Donated to a project with DAI I didn't have

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#60]
## 📋 Anything to add?
Testing on staging.

I had about 80 DAI in my wallet and tried donating 90 DAI

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/7fa6ad01-6997-4c94-9c1f-576180e21795)

Got this notification that the transaction had been reverted:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/f0ac7f70-30f8-467d-8450-0d4877980cbe)

but afterwards the "transaction in progress" popup persisted:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/578e713d-a0a3-4e09-8b4b-db454981e69a)

And when I checked the project, my donation of 90 DAI shows up as having gone through, with nothing actually having left my wallet:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d9a0fdbd-c5f3-4ccc-aea7-e5245ba174b1)

**Comment by divine-comedian** [comment]
I tried donating more xDAI than I have, I receive a pop-up message telling me I have insufficient funds. This seems to be the solution, however I would propose some small semantic/grammar modifications. 

Proposing: 
`Insufficient funds for transfer using address: <ADDRESS>`

![image](https://user-images.githubusercontent.com/67759413/129221315-0cfa2c74-8aec-4680-86a0-6fff621347d4.png)

**Comment by mateodaza** [comment]
Sadly that message comes straight from the wallet provider, not sure if they all have the same error code convention to modify the message we display. So I'd rather leave it as it is

**Comment by divine-comedian** [comment]
Okay! We'll call this one tested and done then. :)
