### ISSUE TITLE
Change URL on a project

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-next#616]
I changed the title of my Giveth project and would like for the URL to reflect this change.

Prpject: Teva Natural Birth Sanctuary

Currently url: /teva-natural-birth-micro-village

**Comment by MoeNick** [comment]
Both old and new URLs are working fine, it;s a feature to avoid broken links if there were used somewhere before editing.

**Comment by ForestSoleil** [comment]
Thank you moe nick! This works.
