### ISSUE TITLE
As a project owner should see the quality score of my project and an explanation thereof

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-next#62]
As a project owner should see the quality score of my project with a perhaps a tooltip explaining how the quality score is calculated. This score is used to rank search results, and we should explain and motivate users to improve the quality of their project through this.
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/9b97ccf3-efa1-4453-b899-63c1855a32fc)

**Comment by MoeNick** [comment]
@laurenluz @divine-comedian 
Any updates on what we decided? 
If we decided on  the progress bar - % compelete we can groom and plan for it today.
