### ISSUE TITLE
Support page typeform links need updated

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#621]
We upgraded the typeform account. I didnt realize that all of the links connected to that account would be changed. 
Currently they go to a redirect page but it would be nice to update them to the correct link

![image](https://user-images.githubusercontent.com/74267818/148469592-055d2da1-db84-4f4f-98e4-7b24cdf0106f.png)

Here are the updated links:
Ask us a Question - https://giveth.typeform.com/question
Report an issue - https://giveth.typeform.com/issue-bug
Leave Feedback - https://giveth.typeform.com/feedback
Request a New Feature - https://giveth.typeform.com/featurerequest

**Comment by mateodaza** [comment]
@WhyldWanderer all this info comes from contentful. A property called onboardingLink.
Can you check in the dashboard?

**Comment by WhyldWanderer** [comment]
HAHA!! I fixed it! Take that contentful!!

Thanks @mateodaza I didnt realize i could fix this myself.
Tested it and the new links are working.
