### ISSUE TITLE
Can't open "My donations" until trying several times...

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#623]
it asks me to sign to authenticate... even though I was already connected... and then gives me a blank giveth screen

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/80c85d90-0c2e-42d7-9329-8656d688b766)

... I had to do it 3x before it worked properly

**Comment by MoeNick** [comment]
@mohammadranjbarz 
Might be related to Rate-Limit?

**Comment by mateodaza** [comment]
@laurenluz you still getting this?
