### ISSUE TITLE
Save failed donations in FE and retry it later

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-next#633]
- [ ] Save exception in FE
- [x] Send an event to Sentry
- [x] FE will retry it.

**Comment by mateodaza** [comment]
This sounds like a good [strategy](https://www.apollographql.com/docs/react/api/link/apollo-link-retry/) using apollo link retry - will try it out

**Comment by mateodaza** [comment]
Apollo Link Retry handles this problem, no need to save the failed donation on store
