### ISSUE TITLE
weird error on updating project update

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#636]
**Please describe the issue or bug you are experiencing:**
Tried to update the Commons Stack Project and got a weird error even tho the update worked
![image](https://api.typeform.com/responses/files/3198e3c3cbdf5e851d382f473ad3ba2e7142d1a21f361e426d174374c70d18c9/Screen_Shot_2022_01_10_at_3.43.11_PM.png)

**Comment by mateodaza** [comment]
duplicate #614
