### ISSUE TITLE
Links on the support page are broken

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#637]
**Please describe the issue or bug you are experiencing:**
The Links on the support page and all other links to the typeform need to change because we changed the typeform link
![image](https://api.typeform.com/responses/files/cec89af0d31e28ada7c148e0be74a14c915abd9511bb1e18a4c2d1ac8f5d8851/Screen_Shot_2022_01_10_at_3.48.42_PM.png)

**Comment by WhyldWanderer** [comment]
There is already an issue for this here:
https://github.com/Giveth/giveth-next/issues/621
