### ISSUE TITLE
Donating does not affect total amount raised

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#643]
I made a donation this morning in GIV..

My donations successfully shows on the project page and in 'my donations' but the total amount raised did not change at all.

![image](https://user-images.githubusercontent.com/74267818/149525093-10703262-ee0a-42d7-854f-d0b3ec56ad20.png)

**Comment by WhyldWanderer** [comment]
tx: https://blockscout.com/poa/xdai/tx/0x2a63f2a4fc7d3470c3967ee6b8976f9cc731b1c41590ce7615604edd621843c6

**Comment by CarlosQ96** [comment]
@WhyldWanderer Just notified and Mohammed added the method to update the total amount to his PR that fills GIV price.
