### ISSUE TITLE
Add ability to filter by slug in AdminBro

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#646]
Is it possible to add this function? @mateodaza @CarlosQ96

**Comment by MoeNick** [comment]
Yes, it could be, @CarlosQ96 can you provide an estimation for it?
@WhyldWanderer we currently planned for 2 weeks, if we find bandwidth we can include in our unplanned budget, but probably it takes more than 2 weeks.

**Comment by CarlosQ96** [comment]
AdminBro should have that functionality, I would add it.

**Comment by MoeNick** [comment]
It's tiny, so I bring it to this sprint FYI ;) @CarlosQ96

**Comment by WhyldWanderer** [comment]
Awesome! Thanks guys... 
Its not a rush.. just a nice to have.

**Comment by CarlosQ96** [comment]
@WhyldWanderer I activated the filter. please double check in staging. It was just turning a configuration on.

**Comment by WhyldWanderer** [comment]
After logging into Adminbro on staging, I clicked project on the left hand side and got this..
Not sure if its related to the slug thing, but i havent been able to get the list of projects to populate.

![image](https://user-images.githubusercontent.com/74267818/150351168-5cf18f1e-228c-44ce-8b64-cc71f1989c35.png)

![image](https://user-images.githubusercontent.com/74267818/150351256-a2692806-d38f-4fcd-a41e-9b3c5f4f0f11.png)

**Comment by CarlosQ96** [comment]
Investigating the issue. It seems to get stuck, sometimes it returns the projects but most of the time throws and error.

**Comment by CarlosQ96** [comment]
@MoeNick after restarting the nginx of the server this was fixed. It seems something hang up in the deploy. But Ashley tested again after restarting all and it worked fine!

**Comment by WhyldWanderer** [comment]
Tested and confirmed working on staging!
![image](https://user-images.githubusercontent.com/74267818/155196452-e620cf0a-35c1-4126-84fb-c6b677aad85d.png)
