### ISSUE TITLE
Add explanatory popup on "set eth address" page in create project flow

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#65]
For this:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/b7e0e8d7-2ee1-441a-8721-08d7bc8c5213)

Add popup link below the "You can set..." text that says "What is an ETH address?"

Text for the pop-up:

> Your ETH address, also known as an ERC20 address, is the receiving address for your Ethereum wallet. This is where funds raised by your project will be sent.
> 
> If you logged using Torus via your email or social media. You can access your wallet [here](https://app.tor.us/). Learn more about Ethereum wallets [here](https://ethereum.org/en/wallets/).

This is as per user-feedback and discussion in comms. Ref: https://github.com/Giveth/giveth-planning/issues/207

@markoprljic are you ok w this, design-wise?

**Comment by MoeNick** [comment]
User cant go through pop-up and click on provided links, because is just shown while cursor is over the "what is ETH address" 
may be we can use another modal or let the user close the pop up.

**Comment by divine-comedian** [comment]
@MoeNick you can actually mouse over to the pop-up and click the links, it's just that the text element for `What is an ETH Address` is very small so you need to move your cursor very carefully.

 I would suggest increasing the size of the element and changing the format so it's more clear that the text itself is not a link but opens a hover tooltip - maybe bolding the text, making it appear as a button or a small circular `?` symbol

**Comment by laurenluz** [comment]
this works fine... it's pretty clear to me how to interact w the tooltip

![image](https://user-images.githubusercontent.com/75490971/130525029-10976356-c914-4147-bce0-86d1a6099f34.png)
