### ISSUE TITLE
Add popcorn to our partners and friends page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#663]
@divine-comedian can you do this?

Logo
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/aa4a68e5-fa81-4d2a-acfc-16ce679482e6)

Tagline
Aiding a revolutionary shift in global systems through accessible DeFi products that align financial wellbeing with positive global impact.

Link
https://popcorn.network/

Not sure if you had a particular system for the partners and friends page

**Comment by divine-comedian** [comment]
DONE! also created an issue to make sure our partnerships are kept up to date for the typescript version

**Comment by laurenluz** [comment]
You da best Meechie
