### ISSUE TITLE
Notify project owners when their project gets cancelled

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#67]
Related to Giveth/giveth-2#604 

Right now we are curating projects as a team by communicating internally when we notice a project that looks scammy/sketchy and then @geleeroyale is manually cancelling them if we determine it is appropriate.

We should notify project owner when their projects get cancelled, giving them an opportunity to potentially remedy the issue

**Comment by divine-comedian** [comment]
related to #33 and ready to be tested, the email flow is already designed. 
 
 In order to automate notifying project owners  an admin needs to trigger the deactiveProject method on the impact-graph  rather than changing values directly in the database.
 
 it raises perhaps a larger architecture issues if there exists a super user or admin role  within the impact-graph that would have permission to trigger methods on projects of which they are not the owner and how to prevent users from re-activating their project on the UI after an 'admin' has deactivated it.. 
 
 more to discuss maybe with @mateodaza  @cquinterom096  and @geleeroyale

**Comment by divine-comedian** [comment]
@mateodaza  might be worth revisiting this issue while we are building the mutations for listing/unlisting projects

**Comment by divine-comedian** [comment]
Following discussion in Discord we need to build a function/mutation for an admin to change the status of a project to cancelled and that the user can't re-activate the project themselves. @MoeNick any thoughts on priority?  Do you think this is a task for @mohammadranjbarz  this will be important for us to make our admin dashboard more secure and allow for more integration with connected applications to the impact-graph

**Comment by MoeNick** [comment]
@divine-comedian 
Admin dashboard is high priority and so the related functions are.
I assigned it to @mohammadranjbarz on backed side, 
But a question, all the de-activated projects only can be activated by admins? or just the one which is deactivated by the admin. I mean, if a project is get de-activated by a PM, should it get activaed by himself or just admin can do this?

**Comment by divine-comedian** [comment]
currently a project owner can de-activate their project and re-activate it if they so choose from their projects' page.
![image](https://user-images.githubusercontent.com/67759413/134404157-7cd1707f-9e37-46b2-bcb2-fe7a9418729a.png)

however what we need is a mutation that can be called which will change a project's status to cancelled and can only be called by an "admin". The user, when their project is cancelled by an admin, should not be able to re-activate their project.

**Comment by divine-comedian** [comment]
I noticed in projectResolver.ts we have this code already - 
```
async updateProjectStatus (
    projectId: number,
    status: number,
    user: User
  ): Promise<Boolean> {
    const project = await Project.findOne({ id: projectId })

    if (project) {
      if (project.mayUpdateStatus(user)) {
        const projectStatus = await ProjectStatus.findOne({ id: status })
        if (projectStatus) {
          project.status = projectStatus
          await project.save()
          return true
        } else {
          throw new Error('No project status found, this should be impossible')
        }
      } else {
        throw new Error(
          'User does not have permission to update status on that project'
        )
      }
    } else {
      throw new Error('You tried to deactivate a non existant project')
    }
  }
  ```
  
  however its not related to any mutation on graphql - would this be a helpful place to start?

**Comment by mohammadranjbarz** [comment]
@MoeNick  @divine-comedian 
Sorry I didn't get your point, do we talk about deactivating givethio projects or deactivate trace campaigns from givethio admin panel?

**Comment by MoeNick** [comment]
First consider giveth.io projects to avoid complexity. I will tell u about it in our local daily meeting. @mohammadranjbarz

**Comment by mateodaza** [comment]
@MoeNick can we close this? I believe segment is handling this

**Comment by divine-comedian** [comment]
this is being done by segment/autopilot
