### ISSUE TITLE
Scrape more information from Giving Block projects

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#670]
Currently we are only scraping the Mission Statement and video (if available) from the Giving Block project descriptions. This means that a lot of the projects only have one sentence descriptions. It would be nice to see more information about the project.

We should collect
- "Mission Statement" section
- "Why donate Bitcoin to this organization?" section - We need to make sure the heading part is not shown so that it doesn't say Bitcoin but I think it is possible to scrape the info without the Heading since this currently happens with the "Mission Statement" heading for these projects.
- Video (if available)
- Website URL

**Comment by MoeNick** [comment]
I'm afraid I can't accept to do it in this nextjs version, hopefully, we can do it in our V2 version maybe a month later.

The importing of these Giving Block projects don't have the expected outcome till now, so I think we’d better do it in the right way and avoid rush decisions. 

Thanks
