### ISSUE TITLE
Admin Dashboard - Add field so that Super Admins can add purple list addresses to projects

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#671]
Fund management addresses that are provided during the verification application process need to be added to the purple list at the start of each round. As an admin, I would like to be able to add these addresses within the AdminBro.

We talked about it in the GIVeconomy call this morning and Mohammad says that we should be able to add this feature.

**Comment by mohammadranjbarz** [comment]
After implementing this we should consider changing `getProjectsRecipients` query to return these addresses as well, (it might be better to rename this query )
https://github.com/Giveth/impact-graph/blob/b789803b3c03c8f28c3a40f9464c2a56db4e86b8/src/resolvers/projectResolver.ts#L1059-L1067

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer 
Now you can add purple address in https://serve.giveth.io/admin/resources/PurpleAddress, I think you are the good one to test it and move it to DONE
(When we deploy it to production and when you fill the purple addresses we can delegate purple address to impact-graph and for every round you don't need to give  me the addresses to add it to config of givback-calculation)

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer  For relate address to project you just need to search project's name as below image, and description is optional

![Screen Shot 1401-01-16 at 17.13.22.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/a159f98f-dd69-4695-af2b-5246927b4214)

**Comment by WhyldWanderer** [comment]
This is working correctly now.. closing the issue
