### ISSUE TITLE
Pop-up to inform donors that a project has not been verified

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#675]
I was talking with Mateo about having a disclaimer for non-verified projects.
I know this will be included in the next version but it seems important right now.

I have seen multiple projects coming in for efforts in Ukraine and I would hate for people to get scammed. Although these projects meet the requirements for listing, im not sure all of them are legit. I think it would be a good idea to have a little pop-up somewhere that informs donors that these projects have not been verified by the Giveth team. 

@mosaeedi to design the pop-up
@markoprljic to review
@mateodaza to implement hot-fix when design is ready.

Should say something like "This project has not been verified by the Giveth team. Please do your own research." or something along those lines.

**Comment by markoprljic** [comment]
@WhyldWanderer Isn't the already existing "Verified" badge not enough for this? Curious to know (I may have missed it) where it will be included in the next version, and again ... why when we already have the verified badge?
Thanks for clarifying.

**Comment by WhyldWanderer** [comment]
My understanding of it being included in the next version is based off of a conversation that I had with Mateo:
![image](https://user-images.githubusercontent.com/74267818/156452107-0b4617b6-9231-4009-8222-25ecaafe12d6.png)

Ive just seen quite a few projects coming in around the situation in the Ukraine and although these projects would pass requirements for listing, they may not be legitimate projects. My concern was that with so many people in the world wanting to help ukraine they may get scammed by donating to a project that is on the platform, has been listed, but has not been verified. I thought that having a disclaimer may be a good idea... i ran the idea past Mateo and then made the post in the design channel...

**Comment by markoprljic** [comment]
Shouldn't the user do their own research anyway? I don't think we should emphasize even more the non verified projects, which leaves a negative impression rather than providing value. 
Let alone the verified badge makes user think that all other projects are not worth or safe to donate, which is not the UX we want IMHO.

I'd love to do some research and run user interviews to validate all this.

**Comment by markoprljic** [comment]
@Tosinolawale Can help us with user research.

**Comment by Tosinolawale** [comment]
Hello Everyone. Working on this already

**Comment by WhyldWanderer** [comment]
@markoprljic I totally agree and its not my intention to discourage donations to unverified projects..
Maybe a pop-up is not the correct approach but a less 'in your face' approach.

maybe its better and sufficient just to have a "*this project has not been researched by the Giveth team" at the bottom of the project description or on the page somewhere.

My thoughts are that I want to protect donors from getting scammed and also direct donations to legitimate projects that have actually been researched by the team. After the crisis in Ukraine began, we were getting tons of projects being created by all sorts of people who could very well be scammers. When there is a crisis such as this, donors just want to give to the casuee and I want to facilitate trust in this interaction.

Its not obvious that 'unverified' projects havent been researched any way other than to make sure that the brief description that they enter isnt in violation of Terms of Use. 

Tossynee and I had a sync this morning to discuss how we can facilitate this without ading negative connotation to projects that are legit but havent yet been approved.

**Comment by markoprljic** [comment]
Putting this on hold while we receive user feedback.

**Comment by mosaeedi** [comment]
@Tosinolawale do we have new data regarding this issue?

**Comment by Tosinolawale** [comment]
> @Tosinolawale do we have new data regarding this issue?

No, Old Issue. Should be closed in my Opinion

**Comment by WhyldWanderer** [comment]
@Tosinolawale 
The user research or surveys didn't provide any insight in this instance?

**Comment by Tosinolawale** [comment]
> @Tosinolawale The user research or surveys didn't provide any insight in this instance?
@WhyldWanderer it did.  Verified projects with the Verification badge and Givebacks eligibility is a subtle way of encouraging and informing users to donate to the project. Now the prevailing sentiment from the interviews I conducted is that most users do not interact a lot with yet to be verified projects and a having a disclaimer on such projects subconsciously leaves a negative connotation (Something like "A non Verified project should not be listed on the platform, only list and make donation possible after it has  passed verification process"). 

Although sentiment on that is somewhat balanced for total newbie users;  some feels it is unnecessary while others think having a an additional reminder that a project is not verified doesn't hurt.  If I am going with quantitative data, 75% of the interviewed users think the Verified badge and the reinforced GIVbacks on the new Project card is enough information.

**Comment by mosaeedi** [comment]
@Tosinolawale Can we close this task? or do we still need to keep it here? or maybe we need to create another task based on the information we have and continue there?

**Comment by Tosinolawale** [comment]
> @Tosinolawale Can we close this task? or do we still need to keep it here? or maybe we need to create another task based on the information we have and continue there?

Keep it Open. I will work on it based on the info we have this week

**Comment by WhyldWanderer** [comment]
This has been incorporated into the design on the project single page.. closing this issue
