### ISSUE TITLE
'Subscribe' button on subscribe to our newsletter does nothing

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-next#68]
Testing on next.giveth
Brave browser clean cache and cookies

Trying to enter my email and subscribe to our newsletter, I click `Subscribe` and it does nothing... help

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/549dbd8f-44c5-4ecd-9d26-3244e1c20859)

**Comment by mateodaza** [comment]
Same as #30
