### ISSUE TITLE
When trying to save edits to my project, I receive an error stating that I am not the project owner.

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#69]
Testing on next.giveth.io with chrome and metamask

When I try to edit my project, it allows me to access it and enter the edits however, when I try to save the edits it says I am not the project owner.
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/ee84e1cb-c187-4389-8082-5988881c1444)

Console view:
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/39325dce-54a8-4d49-a333-ede9870ec4bf)

**Comment by mateodaza** [comment]
Is this still happening?

**Comment by WhyldWanderer** [comment]
I tested all of my projects and made a new one with quotes in the title and i was able to edit all of them successfully on next.giveth.io with chrome and metamask
