### ISSUE TITLE
Styles loading with delay

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-next#78]
## 📋 Anything to add?
Styles are loaded only after first render - suggests we need to integrate styling more into ssr.

Found this, might help:
https://dev.to/rsanchezp/next-js-and-styled-components-style-loading-issue-3i68
https://dev.to/aprietof/nextjs--styled-components-the-really-simple-guide----101c

**Comment by mateodaza** [comment]
Did all that config management, only thing they recommend that I didn't have was 'preprocessing' on false - maybe it made a bit difference

Also I upgraded to latest NextJs Version, we can keep this on track and come back later if we feel we can do more optimization
