### ISSUE TITLE
Images on project cards fail to load 

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-next#79]
## 📋 Anything to add?

Mainly on projects list. They are usually slow to load or they don't load at all. Great chances it relates to #78 as it only occurs on main 

![image.png](https://images.zenhubusercontent.com/5f7dde8da5e87776be5215af/fffc469e-8640-44f3-bfc6-d409de39a41c)

notice the gray spot

**Comment by laurenluz** [comment]
seems to be working just fine

![image](https://user-images.githubusercontent.com/75490971/122274137-756afd80-ce9f-11eb-8bc4-c92fcf20b0bd.png)
