### ISSUE TITLE
Mark verified projects as verified in the database

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-next#85]
These projects have been successfully verified and the value in the database needs to be switched to true

https://giveth.io/project/diamante-luz-center-for-regenerative-living
https://giveth.io/project/The-Commons-Simulator:-Level-Up!
https://giveth.io/project/commons-stack:-iteration-0
https://giveth.io/project/Bridging-Digital-Communities-1
https://giveth.io/project/mycrypto/
https://giveth.io/project/bloom-network/
https://giveth.io/project/free-the-food/
https://giveth.io/project/colorado-multiversity/

**Comment by mateodaza** [comment]
Just made the change in our database, I will work on the badge to show this differentiator on our frontend

**Comment by MoeNick** [comment]
@mateodaza do we have an issue for verified project badge?

**Comment by WhyldWanderer** [comment]
@MoeNick i think it is here: https://github.com/Giveth/giveth-next/issues/48

**Comment by WhyldWanderer** [comment]
These projects now have been marked verified in the database and have badges...
Thanks Mateo!
