### ISSUE TITLE
Delay in donation appearing on Campaign is waaaay toooo loooonnnggggg

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-next#87]
Transaction completed in a minute on Etherscan.. why not on Giveth yet nearly an hour later?
![image](https://user-images.githubusercontent.com/39466970/122153848-a6541f80-ce18-11eb-917f-902086034351.png)

## 📋 Anything to add?
This is torture!

## ⏰ Urgency/Deadline/Blockers?
A donor should see their donation appear after making it!

## ❓ Why is it important?
Because Givers won't keep giving to more projects if the first one takes so long!

**Comment by divine-comedian** [comment]
@Danibelle  was it an anonymous donation or were you logged into giveth?

**Comment by mateodaza** [comment]
> @Danibelle was it an anonymous donation or were you logged into giveth?

It was logged in

**Comment by mateodaza** [comment]
I made a workaround to save the donation even if the segment tracking fails 

We still need to see what's happening.

**Comment by mateodaza** [comment]
Created this [issue](https://github.com/Giveth/impact-graph/issues/96) on the impact graph, will close as it's no longer a problem for the frontend
