### ISSUE TITLE
Updates with no Title do not get submitted but show the "project update added successfully" popup

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#91]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/12b985c7-df0e-4d4b-9e60-913209c76a28)

**Comment by divine-comedian** [comment]
I went a bit crazy testing this one out... 
![image](https://user-images.githubusercontent.com/67759413/122821996-85258000-d2ab-11eb-9043-87813678fd21.png)

Could not reproduce the project update pop-up while trying to submit without a title. this looks to be solved!
