### ISSUE TITLE
After I edit an update, the order of updates is no longer chronological

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#92]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a25bb1c9-7bf1-437d-84d1-9fa7bc47a5f3)

**Comment by divine-comedian** [comment]
looks like project updates hold their place in chronological order

![image](https://user-images.githubusercontent.com/67759413/124393331-fca1d900-dcc7-11eb-8502-6771c9743173.png)
