### ISSUE TITLE
Grammar Issue: When submitting an edit to a project update... should say "Save" not "Complete Edition"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#93]
"Complete Edition" is awkward, gramatically...

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e5beb924-cd20-4694-ba01-bbad008234ef)

FYI
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/bb1f2fbe-3823-4b8a-8cbb-b5e7fc476b9a)

**Comment by divine-comedian** [comment]
Text looks to be updated! 
Currently on `next.giveth`

![image](https://user-images.githubusercontent.com/67759413/122823636-9d969a00-d2ad-11eb-83ef-cb9dab2b8f83.png)
