### ISSUE TITLE
Can't find my new project "my perfect project" on projects page or using search function

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-next#94]
I just made a new test project "my perfect project" https://next.giveth.io/project/my-perfect-project-1

but it doesn't show up on the projects page or when I search. It does, however, show up under "my projects"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/de713819-4396-460f-b6d1-c1cc91a95acb)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e6c84612-1dad-465d-b7c8-daf8f4d54cdb)

**Comment by mateodaza** [comment]
so uhmm 

![image](https://user-images.githubusercontent.com/18689480/122276541-810ff180-ceaa-11eb-85aa-6a1b2a705c2d.png)

I believe this is cause of some caching thing, which I don't believe it's an issue, but it's now showing
