### ISSUE TITLE
Number of Givers on Project is Zero

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-next#95]
This seems to be for all projects, wondering if it is just me?
I also cannot heart projects again *sigh
![image](https://user-images.githubusercontent.com/39466970/122150312-4eb2b580-ce12-11eb-99da-422cee1cbfc3.png)

@

**Comment by mateodaza** [comment]
on it :)) - it was easy fix

**Comment by Danibelle** [comment]
Works now!!
